from typing import Dict
from ..items import SongData

SONG_DATA: Dict[str, SongData] = {
    "Rainbow Dream":  SongData(10, "Rainbow Dream", "WACCA", "TANO*C（オリジナル）", [3, 8.7, 11, None]),
    "Knight Rider":  SongData(11, "Knight Rider", "WACCA", "TANO*C（オリジナル）", [6, 10.7, 13, None]),
    "Poseidon":  SongData(12, "Poseidon", "WACCA", "TANO*C（オリジナル）", [5, 9.7, 13.7, None]),
    "PARALLEL★PRISM":  SongData(13, "PARALLEL★PRISM", "WACCA", "TANO*C（オリジナル）", [3, 7.7, 10.7, None]),
    "千本桜":  SongData(14, "千本桜", "WACCA", "ボカロ", [2, 7.7, 10, None]),
    "ピースサイン":  SongData(15, "ピースサイン", "WACCA", "アニメ／ＰＯＰ", [2, 6.7, 9.7, None]),
    "MEMORiZE":  SongData(16, "MEMORiZE", "WACCA", "TANO*C", [3, 8, 10, None]),
    "illanai-assorted":  SongData(17, "illanai-assorted", "WACCA", "TANO*C", [4, 8.7, 12.7, None]),
    "ファティマ":  SongData(18, "ファティマ", "WACCA", "アニメ／ＰＯＰ", [2, 6.7, 9, None]),
    "Soldiers":  SongData(19, "Soldiers", "WACCA", "TANO*C", [4, 8.7, 11.7, None]),
    "Fight for the CORE feat. Daisuke":  SongData(20, "Fight for the CORE feat. Daisuke", "WACCA", "TANO*C", [4, 10.7, 12, None]),
    "エイリアンエイリアン":  SongData(21, "エイリアンエイリアン", "WACCA", "ボカロ", [2, 6.7, 10, None]),
    "砂の惑星 feat. 初音ミク":  SongData(22, "砂の惑星 feat. 初音ミク", "WACCA", "ボカロ", [3, 8.7, 10, None]),
    "マトリョシカ":  SongData(23, "マトリョシカ", "WACCA", "ボカロ", [3, 8, 10, None]),
    "Let you DIVE!":  SongData(24, "Let you DIVE!", "WACCA", "オリジナル", [3, 9.7, 11.7, 13, None]),
    "徒花ネクロマンシー":  SongData(25, "徒花ネクロマンシー", "WACCA", "アニメ／ＰＯＰ", [3, 6.7, 9.7, None]),
    "POP TEAM EPIC":  SongData(26, "POP TEAM EPIC", "WACCA", "アニメ／ＰＯＰ", [3, 7.7, 11, None]),
    "ようこそジャパリパークへ":  SongData(27, "ようこそジャパリパークへ", "WACCA", "アニメ／ＰＯＰ", [2, 7, 10.7, None]),
    "ロキ":  SongData(28, "ロキ", "WACCA", "ボカロ", [4, 9, 11, None]),
    "ウマーベラス":  SongData(29, "ウマーベラス", "WACCA", "アニメ／ＰＯＰ", [1, 6.7, 9.7, None]),
    "ギミチョコ!!":  SongData(30, "ギミチョコ!!", "WACCA", "アニメ／ＰＯＰ", [4, 10, 12.7, None]),
    "ウミユリ海底譚":  SongData(31, "ウミユリ海底譚", "WACCA", "ボカロ", [1, 7, 10, None]),
    "Seyana. ～何でも言うことを聞いてくれるアカネチャン～":  SongData(32, "Seyana. ～何でも言うことを聞いてくれるアカネチャン～", "WACCA", "ボカロ", [2, 9, 11.7, None]),
    "フラジール":  SongData(33, "フラジール", "WACCA", "ボカロ", [1, 7, 10, None]),
    "ルーンファクトリー４スペシャルより「この想いを乗せて」":  SongData(34, "ルーンファクトリー４スペシャルより「この想いを乗せて」", "WACCA", "バラエティ", [1, 5, 9, None]),
    "LEVATEiN feat. 野宮あゆみ":  SongData(35, "LEVATEiN feat. 野宮あゆみ", "WACCA", "TANO*C（オリジナル）", [4, 9, 12, None]),
    "BIG HEAD BANGING":  SongData(36, "BIG HEAD BANGING", "WACCA", "TANO*C（オリジナル）", [6, 11, 13.7, None]),
    "Quon":  SongData(37, "Quon", "WACCA", "TANO*C（オリジナル）", [5, 10, 12.7, 13.7, None]),
    "HELL FLAME":  SongData(38, "HELL FLAME", "WACCA", "TANO*C（オリジナル）", [5, 10, 12.7, 13.7, None]),
    "Gate One":  SongData(39, "Gate One", "WACCA", "TANO*C（オリジナル）", [4, 9, 12, None]),
    "Are You Ready":  SongData(40, "Are You Ready", "WACCA", "TANO*C（オリジナル）", [4, 10, 12, None]),
    "Over My Hand":  SongData(41, "Over My Hand", "WACCA", "TANO*C（オリジナル）", [3, 9, 11, None]),
    "Sunshine":  SongData(42, "Sunshine", "WACCA", "TANO*C", [4, 8, 11, None]),
    "Try again":  SongData(43, "Try again", "WACCA", "TANO*C", [4, 8.7, 10, None]),
    "Ever Free(Raw Edit)":  SongData(44, "Ever Free(Raw Edit)", "WACCA", "TANO*C", [3, 8, 10, None]),
    "BOOM! BOOM!! BOOM!!!":  SongData(45, "BOOM! BOOM!! BOOM!!!", "WACCA", "TANO*C", [4, 10, 12, None]),
    "BLUE SKY feat. 野宮あゆみ":  SongData(46, "BLUE SKY feat. 野宮あゆみ", "WACCA", "TANO*C", [3, 7, 10, None]),
    "Sound Chimera":  SongData(47, "Sound Chimera", "WACCA", "TANO*C", [5, 10.7, 12.7, 13.7, None]),
    "Nameless Story":  SongData(48, "Nameless Story", "WACCA", "アニメ／ＰＯＰ", [3, 7, 10, None]),
    "TOMORROW":  SongData(49, "TOMORROW", "WACCA", "アニメ／ＰＯＰ", [3, 8, 10, None]),
    "五等分の気持ち":  SongData(50, "五等分の気持ち", "WACCA", "アニメ／ＰＯＰ", [2, 6, 9.7, None]),
    "ゲームオーバー (feat. TORIENA)":  SongData(51, "ゲームオーバー (feat. TORIENA)", "WACCA", "バラエティ", [2, 7.7, 11.7, None]),
    "ファッとして桃源郷":  SongData(52, "ファッとして桃源郷", "WACCA", "アニメ／ＰＯＰ", [3, 9, 12, None]),
    "乙女解剖":  SongData(53, "乙女解剖", "WACCA", "ボカロ", [3, 7, 9, None]),
    "スクランブル交際":  SongData(54, "スクランブル交際", "WACCA", "ボカロ", [3, 8, 11, None]),
    "Shining Harmony":  SongData(55, "Shining Harmony", "WACCA", "TANO*C", [4, 9, 12, None]),
    "EZ DO DANCE -K.O.P. REMIX-":  SongData(56, "EZ DO DANCE -K.O.P. REMIX-", "WACCA", "アニメ／ＰＯＰ", [1, 6, 9, None]),
    "かくしん的☆めたまるふぉ～ぜっ!":  SongData(57, "かくしん的☆めたまるふぉ～ぜっ!", "WACCA", "アニメ／ＰＯＰ", [1, 5, 9, None]),
    "シュガーソングとビターステップ":  SongData(58, "シュガーソングとビターステップ", "WACCA", "アニメ／ＰＯＰ", [2, 7, 10, None]),
    "Singin'☆Shine！":  SongData(59, "Singin'☆Shine！", "WACCA", "2.5次元", [1, 5, 9, None]),
    "Jingle":  SongData(60, "Jingle", "WACCA", "TANO*C", [4, 9.7, 11, None]),
    "GRiDGALAXY":  SongData(61, "GRiDGALAXY", "WACCA", "TANO*C", [4, 8, 11, None]),
    "BATTLE NO.1":  SongData(62, "BATTLE NO.1", "WACCA", "TANO*C", [6, 10, 13.7, 14, None]),
    "conflict":  SongData(63, "conflict", "WACCA", "バラエティ", [5, 10, 13, None]),
    "こんにちは、ARuFaです。":  SongData(64, "こんにちは、ARuFaです。", "WACCA", "バラエティ", [3, 7, 10, None]),
    "ぼくの夢、メチャクソ無限湧き":  SongData(65, "ぼくの夢、メチャクソ無限湧き", "WACCA", "バラエティ", [4, 9, 12, 13.7, None]),
    "Exitium":  SongData(66, "Exitium", "WACCA", "TANO*C（オリジナル）", [6, 11, 14, None]),
    "EXCITE":  SongData(67, "EXCITE", "WACCA", "アニメ／ＰＯＰ", [1, 6, 10, None]),
    "幸せになれる隠しコマンドがあるらしい":  SongData(68, "幸せになれる隠しコマンドがあるらしい", "WACCA", "ボカロ", [5, 10, 13, None]),
    "Blaze":  SongData(69, "Blaze", "WACCA", "TANO*C", [3, 8.7, 11.7, None]),
    "Source of Creation":  SongData(70, "Source of Creation", "WACCA", "TANO*C", [3, 8, 11, None]),
    "HiGHER":  SongData(71, "HiGHER", "WACCA", "TANO*C", [3, 8, 12, None]),
    "ADAM":  SongData(72, "ADAM", "WACCA", "TANO*C（オリジナル）", [5, 10, 13, None]),
    "ATARAX1A":  SongData(73, "ATARAX1A", "WACCA", "TANO*C（オリジナル）", [4, 8, 12, None]),
    "13 DONKEYS":  SongData(74, "13 DONKEYS", "WACCA", "TANO*C（オリジナル）", [2, 8, 12, None]),
    "Galaxy Friends":  SongData(75, "Galaxy Friends", "WACCA", "TANO*C", [4, 8.7, 12.7, None]),
    "太陽系デスコ":  SongData(76, "太陽系デスコ", "WACCA", "ボカロ", [2, 7, 10.7, None]),
    "気まぐれメルシィ feat. 初音ミク":  SongData(77, "気まぐれメルシィ feat. 初音ミク", "WACCA", "ボカロ", [3, 7, 10, None]),
    "Akareram":  SongData(78, "Akareram", "WACCA", "TANO*C", [3, 8, 11.7, None]),
    "アカリがやってきたぞっ":  SongData(79, "アカリがやってきたぞっ", "WACCA", "ボカロ", [3, 8, 11, None]),
    "WARNING×WARNING×WARNING":  SongData(80, "WARNING×WARNING×WARNING", "WACCA", "東方アレンジ", [3, 7.7, 11, None]),
    "Raise Your Heart!!":  SongData(81, "Raise Your Heart!!", "WACCA", "アニメ／ＰＯＰ", [3, 7, 10, None]),
    "ナイト・オブ・ナイツ":  SongData(82, "ナイト・オブ・ナイツ", "WACCA", "東方アレンジ", [3, 9, 12, None]),
    "SHINY DAYS":  SongData(83, "SHINY DAYS", "WACCA", "アニメ／ＰＯＰ", [1, 5, 9, None]),
    "Bad Apple!! feat. nomico":  SongData(84, "Bad Apple!! feat. nomico", "WACCA", "東方アレンジ", [1, 5, 9, None]),
    "taboo tears you up 2017":  SongData(85, "taboo tears you up 2017", "WACCA", "東方アレンジ", [4, 9.7, 12, None]),
    "チルノのパーフェクトさんすう教室":  SongData(86, "チルノのパーフェクトさんすう教室", "WACCA", "東方アレンジ", [3, 9, 11, None]),
    "集結の華々":  SongData(87, "集結の華々", "WACCA", "バラエティ", [2, 6, 10.7, None]),
    "待チ人ハ来ズ。":  SongData(88, "待チ人ハ来ズ。", "WACCA", "東方アレンジ", [2, 6, 10, None]),
    "The Light":  SongData(89, "The Light", "WACCA", "アニメ／ＰＯＰ", [3, 7.7, 12, None]),
    "AIAIAI (feat. 中田ヤスタカ)":  SongData(90, "AIAIAI (feat. 中田ヤスタカ)", "WACCA", "アニメ／ＰＯＰ", [1, 6, 9, None]),
    "Chariot":  SongData(91, "Chariot", "WACCA", "TANO*C（オリジナル）", [3, 8, 12, None]),
    "Hello, Morning":  SongData(92, "Hello, Morning", "WACCA", "アニメ／ＰＯＰ", [2, 7, 11, None]),
    "VOX Diamond":  SongData(93, "VOX Diamond", "WACCA", "TANO*C", [4, 7.7, 12, None]),
    "Pixel Galaxy":  SongData(94, "Pixel Galaxy", "WACCA", "バラエティ", [2, 7, 10.7, None]),
    "残酷な天使のテーゼ":  SongData(95, "残酷な天使のテーゼ", "WACCA", "アニメ／ＰＯＰ", [1, 5, 9, None]),
    "ただ君に晴れ":  SongData(96, "ただ君に晴れ", "WACCA", "アニメ／ＰＯＰ", [3, 7, 9, None]),
    "Utopia feat. shully":  SongData(97, "Utopia feat. shully", "WACCA", "オリジナル", [5, 9, 12, None]),
    "You Only Live Once":  SongData(98, "You Only Live Once", "WACCA", "アニメ／ＰＯＰ", [1, 5, 9, None]),
    "Honey Panic!":  SongData(99, "Honey Panic!", "WACCA", "バラエティ", [3, 9, 12, None]),
    "Stratoliner":  SongData(100, "Stratoliner", "WACCA", "オリジナル", [4, 9.7, 12.7, None]),
    "劣等上等":  SongData(101, "劣等上等", "WACCA", "ボカロ", [3, 8, 11.7, None]),
    "にめんせい☆ウラオモテライフ!":  SongData(102, "にめんせい☆ウラオモテライフ!", "WACCA", "アニメ／ＰＯＰ", [3, 7.7, 10, None]),
    "FREEDOM DiVE↓":  SongData(103, "FREEDOM DiVE↓", "WACCA", "バラエティ", [6, 10.7, 13.7, None]),
    "初音ミクの消失":  SongData(104, "初音ミクの消失", "WACCA", "ボカロ", [5, 10, 13.7, None]),
    "Invisible Frenzy":  SongData(105, "Invisible Frenzy", "WACCA", "TANO*C（オリジナル）", [7, 11, 14, None]),
    "JINGLE DEATH":  SongData(106, "JINGLE DEATH", "WACCA", "TANO*C（オリジナル）", [4, 10, 13, None]),
    "『エキセントリック少年ボウイ』のテーマ":  SongData(107, "『エキセントリック少年ボウイ』のテーマ", "WACCA", "バラエティ", [1, 5.7, 12, None]),
    "What's this?":  SongData(108, "What's this?", "WACCA", "バラエティ", [3, 6, 10, None]),
    "Over the sweat and tears":  SongData(109, "Over the sweat and tears", "WACCA", "2.5次元", [1, 5, 9, None]),
    "Jägermeister":  SongData(110, "Jägermeister", "WACCA", "バラエティ", [3, 8.7, 11, None]),
    "CHECKER FLAG":  SongData(111, "CHECKER FLAG", "WACCA", "オリジナル", [3, 7, 12.7, None]),
    "BLVST BEVT":  SongData(112, "BLVST BEVT", "WACCA", "TANO*C", [4, 10, 12, None]),
    "jacaranda":  SongData(113, "jacaranda", "WACCA", "オリジナル", [4, 9, 12.7, None]),
    "LOSE CONTROL":  SongData(114, "LOSE CONTROL", "WACCA S", "TANO*C", [3, 8, 11, None]),
    "ロストワンの号哭":  SongData(115, "ロストワンの号哭", "WACCA S", "ボカロ", [4, 8, 12, None]),
    "Demon's Rave":  SongData(116, "Demon's Rave", "WACCA S", "オリジナル", [5, 10, 12.7, None]),
    "Murasaki":  SongData(117, "Murasaki", "WACCA S", "TANO*C（オリジナル）", [3, 7, 12, None]),
    "only my railgun":  SongData(118, "only my railgun", "WACCA S", "アニメ／ＰＯＰ", [3, 6.7, 9, None]),
    "燐廻":  SongData(119, "燐廻", "WACCA S", "バラエティ", [2, 7.7, 11, None]),
    "ナイト・オブ・ナイツ (かめりあ's'ワンス・アポン・ア・ナイト'Remix)":  SongData(120, "ナイト・オブ・ナイツ (かめりあ's'ワンス・アポン・ア・ナイト'Remix)", "WACCA S", "東方アレンジ", [5, 10, 13, None]),
    "Shiny Memory feat.Yukacco":  SongData(121, "Shiny Memory feat.Yukacco", "WACCA S", "TANO*C", [3, 9.7, 12, None]),
    "Mami Mami Zone":  SongData(122, "Mami Mami Zone", "WACCA S", "東方アレンジ", [4, 9, 11, None]),
    "いーあるふぁんくらぶ":  SongData(123, "いーあるふぁんくらぶ", "WACCA S", "ボカロ", [2, 6, 10, None]),
    "オドループ":  SongData(124, "オドループ", "WACCA S", "アニメ／ＰＯＰ", [3, 7.7, 10, None]),
    "悪戯センセーション":  SongData(125, "悪戯センセーション", "WACCA S", "東方アレンジ", [2, 8, 12, None]),
    "ゴーストルール":  SongData(126, "ゴーストルール", "WACCA S", "ボカロ", [3, 9, 11, None]),
    "ドラマツルギー":  SongData(127, "ドラマツルギー", "WACCA S", "アニメ／ＰＯＰ", [2, 7, 10, None]),
    "†DOOF†SENC†":  SongData(128, "†DOOF†SENC†", "WACCA S", "TANO*C", [6, 10, 13, None]),
    "Mazy Metroplex":  SongData(129, "Mazy Metroplex", "WACCA S", "TANO*C（オリジナル）", [4, 10.7, 13.7, None]),
    "シャルル":  SongData(130, "シャルル", "WACCA S", "アニメ／ＰＯＰ", [3, 7, 10, None]),
    "EU over Progress":  SongData(131, "EU over Progress", "WACCA S", "バラエティ", [6, 10.7, 12.7, None]),
    "ベースラインやってる？笑":  SongData(132, "ベースラインやってる？笑", "WACCA S", "バラエティ", [4, 9.7, 12, None]),
    "Shiny Smily Story":  SongData(133, "Shiny Smily Story", "WACCA S", "アニメ／ＰＯＰ", [3, 6, 10, None]),
    "Dream☆Story":  SongData(134, "Dream☆Story", "WACCA S", "アニメ／ＰＯＰ", [2, 7, 11, None]),
    "without U":  SongData(135, "without U", "WACCA S", "アニメ／ＰＯＰ", [3, 7, 10, None]),
    "U.S.A.":  SongData(136, "U.S.A.", "WACCA S", "アニメ／ＰＯＰ", [2, 7, 10, None]),
    "新宝島":  SongData(137, "新宝島", "WACCA S", "アニメ／ＰＯＰ", [1, 6, 9, None]),
    "カゲロウデイズ":  SongData(138, "カゲロウデイズ", "WACCA S", "ボカロ", [4, 9, 11, None]),
    "セツナトリップ":  SongData(139, "セツナトリップ", "WACCA S", "ボカロ", [3, 9, 12, None]),
    "天ノ弱":  SongData(140, "天ノ弱", "WACCA S", "ボカロ", [3, 7, 10, None]),
    "神寂":  SongData(141, "神寂", "WACCA S", "東方アレンジ", [4, 10.7, 13, None]),
    "天狗の落とし文 feat. ytr":  SongData(142, "天狗の落とし文 feat. ytr", "WACCA S", "東方アレンジ", [3, 8, 12, None]),
    "ケロ⑨Destiny":  SongData(143, "ケロ⑨Destiny", "WACCA S", "東方アレンジ", [2, 6, 11.7, None]),
    "LOVE EAST":  SongData(144, "LOVE EAST", "WACCA S", "東方アレンジ", [3, 7, 11, None]),
    "風に乗せた願い":  SongData(145, "風に乗せた願い", "WACCA S", "東方アレンジ", [3, 7, 10, None]),
    "GASHATT":  SongData(146, "GASHATT", "WACCA S", "オリジナル", [4, 10, 12, None]),
    "Strange Bar":  SongData(147, "Strange Bar", "WACCA S", "TANO*C", [3, 10, 12.7, None]),
    "ストライク・ザ・ブラッド":  SongData(148, "ストライク・ザ・ブラッド", "WACCA S", "アニメ／ＰＯＰ", [3, 8.7, 11.7, None]),
    "輪廻転生":  SongData(149, "輪廻転生", "WACCA S", "アニメ／ＰＯＰ", [3, 9, 12, None]),
    "Altale":  SongData(150, "Altale", "WACCA S", "バラエティ", [4, 9, 12, None]),
    "GOODWORLD":  SongData(151, "GOODWORLD", "WACCA S", "バラエティ", [2, 9, 12, None]),
    "Eyes on me feat. Such":  SongData(152, "Eyes on me feat. Such", "WACCA S", "バラエティ", [3, 7.7, 12, None]),
    "君のStarlight Road":  SongData(153, "君のStarlight Road", "WACCA S", "バラエティ", [3, 8, 10, None]),
    "FUJIN Rumble":  SongData(154, "FUJIN Rumble", "WACCA S", "バラエティ", [5, 10.7, 13, None]),
    "BUCHiGiRE Berserker":  SongData(155, "BUCHiGiRE Berserker", "WACCA S", "バラエティ", [4, 10.7, 13.7, None]),
    "聖者の鼓動":  SongData(156, "聖者の鼓動", "WACCA S", "バラエティ", [2, 7, 12, None]),
    "サイクルヒット":  SongData(157, "サイクルヒット", "WACCA S", "TANO*C", [5, 10, 13, None]),
    "Ultra Red":  SongData(158, "Ultra Red", "WACCA S", "TANO*C", [3, 9, 12.7, None]),
    "Brain Power":  SongData(159, "Brain Power", "WACCA S", "バラエティ", [4, 9.7, 13, None]),
    "ガンガン・ドンドン":  SongData(160, "ガンガン・ドンドン", "WACCA S", "2.5次元", [2, 6, 9.7, None]),
    "スマイル・アンド・ティアズ":  SongData(161, "スマイル・アンド・ティアズ", "WACCA S", "2.5次元", [2, 6, 9, None]),
    "STILL HOT IN MY HEART":  SongData(162, "STILL HOT IN MY HEART", "WACCA S", "2.5次元", [3, 7, 10, None]),
    "ぼなぺてぃーと♡S":  SongData(163, "ぼなぺてぃーと♡S", "WACCA S", "アニメ／ＰＯＰ", [2, 7.7, 11, None]),
    "デタラメなマイナスとプラスにおけるブレンド考":  SongData(164, "デタラメなマイナスとプラスにおけるブレンド考", "WACCA S", "アニメ／ＰＯＰ", [2, 5.7, 10, None]),
    "チュルリラ・チュルリラ・ダッダッダ！":  SongData(165, "チュルリラ・チュルリラ・ダッダッダ！", "WACCA S", "ボカロ", [4, 8, 12, None]),
    "おばけのウケねらい":  SongData(166, "おばけのウケねらい", "WACCA S", "ボカロ", [3, 8, 11.7, None]),
    "ベノム":  SongData(167, "ベノム", "WACCA S", "ボカロ", [3, 7, 12, None]),
    "リアル初音ミクの消失":  SongData(168, "リアル初音ミクの消失", "WACCA S", "ボカロ", [6, 10, 13.7, None]),
    "ツアー・ファイナル":  SongData(169, "ツアー・ファイナル", "WACCA S", "TANO*C", [3, 9, 12, None]),
    "XTREME":  SongData(170, "XTREME", "WACCA S", "TANO*C（オリジナル）", [6, 11, 12.7, 14, None]),
    "天使光輪":  SongData(171, "天使光輪", "WACCA S", "TANO*C（オリジナル）", [7, 11, 13, 14, None]),
    "METEOR BURST":  SongData(172, "METEOR BURST", "WACCA S", "TANO*C（オリジナル）", [5, 10.7, 13.7, None]),
    "Metamorphose":  SongData(173, "Metamorphose", "WACCA S", "TANO*C（オリジナル）", [4, 10, 12.7, None]),
    "MAGiC4LG1RL M3GA S7R1KE!":  SongData(174, "MAGiC4LG1RL M3GA S7R1KE!", "WACCA S", "TANO*C（オリジナル）", [4, 10, 13, None]),
    "Bravely You":  SongData(175, "Bravely You", "WACCA S", "アニメ／ＰＯＰ", [1, 6, 9, None]),
    "ダダダダ天使":  SongData(176, "ダダダダ天使", "WACCA S", "アニメ／ＰＯＰ", [3, 7.7, 12, None]),
    "ダンシング☆サムライ":  SongData(177, "ダンシング☆サムライ", "WACCA S", "バラエティ", [3, 7.7, 10, None]),
    "WHITE":  SongData(178, "WHITE", "WACCA S", "バラエティ", [3, 8, 10, None]),
    "GENOCIDER":  SongData(179, "GENOCIDER", "WACCA Lily", "TANO*C（オリジナル）", [6, 11, 14, None]),
    "SUPER REACTOR":  SongData(180, "SUPER REACTOR", "WACCA Lily", "TANO*C（オリジナル）", [4, 8, 13, None]),
    "ONOMATO Pairing!!!":  SongData(181, "ONOMATO Pairing!!!", "WACCA Lily", "TANO*C（オリジナル）", [2, 8, 12, None]),
    "THE MUZZLE FACING":  SongData(182, "THE MUZZLE FACING", "WACCA Lily", "オリジナル", [4, 9.7, 13.7, None]),
    "LETHAL;WEAPON":  SongData(183, "LETHAL;WEAPON", "WACCA Lily", "オリジナル", [3, 8, 12.7, None]),
    "Tell Me":  SongData(184, "Tell Me", "WACCA Lily", "オリジナル", [3, 7.7, 11.7, None]),
    "While Shining feat.Yukacco":  SongData(185, "While Shining feat.Yukacco", "WACCA Lily", "TANO*C", [3, 8, 12, None]),
    "ALiVE":  SongData(186, "ALiVE", "WACCA Lily", "TANO*C", [3, 7.7, 11, None]),
    "ニュー・ウェーブ":  SongData(187, "ニュー・ウェーブ", "WACCA Lily", "2.5次元", [2, 6, 9, None]),
    "インドア系ならトラックメイカー":  SongData(188, "インドア系ならトラックメイカー", "WACCA Lily", "バラエティ", [2, 7, 12.7, None]),
    "Calamity Fortune":  SongData(189, "Calamity Fortune", "WACCA Lily", "東方アレンジ", [4, 10, 13.7, None]),
    "ゆけむり魂温泉 II":  SongData(190, "ゆけむり魂温泉 II", "WACCA Lily", "東方アレンジ", [3, 7, 12, None]),
    "明星ロケット":  SongData(191, "明星ロケット", "WACCA Lily", "東方アレンジ", [2, 7, 11.7, None]),
    "ブリキノダンス":  SongData(192, "ブリキノダンス", "WACCA Lily", "ボカロ", [3, 7.7, 12, None]),
    "Gimme×Gimme feat. 初音ミク・鏡音リン":  SongData(193, "Gimme×Gimme feat. 初音ミク・鏡音リン", "WACCA Lily", "ボカロ", [2, 8, 12, None]),
    "ポジティブ☆ダンスタイム":  SongData(194, "ポジティブ☆ダンスタイム", "WACCA Lily", "ボカロ", [3, 8.7, 11, None]),
    "39みゅーじっく！":  SongData(195, "39みゅーじっく！", "WACCA Lily", "ボカロ", [2, 7, 10.7, None]),
    "ハート♥イロ♥トリドリ〜ム":  SongData(196, "ハート♥イロ♥トリドリ〜ム", "WACCA Lily", "アニメ／ＰＯＰ", [1, 6, 10, None]),
    "キラッとスタート":  SongData(197, "キラッとスタート", "WACCA Lily", "アニメ／ＰＯＰ", [2, 7, 10, None]),
    "キラッとスタート (USAO Remix)":  SongData(198, "キラッとスタート (USAO Remix)", "WACCA Lily", "アニメ／ＰＯＰ", [4, 8, 12, None]),
    "Make it！":  SongData(199, "Make it！", "WACCA Lily", "アニメ／ＰＯＰ", [1, 5, 9, None]),
    "Make it！ (DJ Genki Remix)":  SongData(200, "Make it！ (DJ Genki Remix)", "WACCA Lily", "アニメ／ＰＯＰ", [3, 7.7, 11, None]),
    "キラメキライダー☆":  SongData(201, "キラメキライダー☆", "WACCA Lily", "アニメ／ＰＯＰ", [2, 7, 11, None]),
    "This game":  SongData(202, "This game", "WACCA Lily", "アニメ／ＰＯＰ", [2, 7, 10.7, None]),
    "ガヴリールドロップキック":  SongData(203, "ガヴリールドロップキック", "WACCA Lily", "アニメ／ＰＯＰ", [3, 6.7, 11, None]),
    "RAGE OF DUST":  SongData(204, "RAGE OF DUST", "WACCA Lily", "アニメ／ＰＯＰ", [3, 8, 9, None]),
    "HOT LIMIT":  SongData(205, "HOT LIMIT", "WACCA Lily", "アニメ／ＰＯＰ", [3, 7.7, 10, None]),
    "ないものねだり":  SongData(206, "ないものねだり", "WACCA Lily", "アニメ／ＰＯＰ", [2, 7.7, 11, None]),
    "秒針を噛む":  SongData(207, "秒針を噛む", "WACCA Lily", "アニメ／ＰＯＰ", [2, 6.7, 11, None]),
    "with U":  SongData(208, "with U", "WACCA Lily", "オリジナル", [3, 7.7, 11.7, 13, None]),
    "脳漿炸裂ガール":  SongData(209, "脳漿炸裂ガール", "WACCA Lily", "ボカロ", [5, 9, 13, None]),
    "ヒビカセ":  SongData(210, "ヒビカセ", "WACCA Lily", "ボカロ", [3, 8, 12, None]),
    "アスノヨゾラ哨戒班":  SongData(211, "アスノヨゾラ哨戒班", "WACCA Lily", "ボカロ", [3, 7, 11.7, None]),
    "Poppin' Shower":  SongData(212, "Poppin' Shower", "WACCA Lily", "TANO*C", [3, 9.7, 12, None]),
    "Grayed Out-Antifront-":  SongData(213, "Grayed Out-Antifront-", "WACCA Lily", "バラエティ", [3, 9, 13, None]),
    "ARTEMiS":  SongData(214, "ARTEMiS", "WACCA Lily", "オリジナル", [4, 10, 13.7, None]),
    "進捗どうですか？":  SongData(215, "進捗どうですか？", "WACCA Lily", "東方アレンジ", [3, 8, 12, None]),
    "Help me, ERINNNNNN!!":  SongData(216, "Help me, ERINNNNNN!!", "WACCA Lily", "東方アレンジ", [3, 7.7, 11, None]),
    "Sweet Requiem":  SongData(217, "Sweet Requiem", "WACCA Lily", "東方アレンジ", [3, 9, 12.7, None]),
    "トロピカッ☆バケーション":  SongData(218, "トロピカッ☆バケーション", "WACCA Lily", "アニメ／ＰＯＰ", [2, 7, 10.7, None]),
    "over and over":  SongData(219, "over and over", "WACCA Lily", "アニメ／ＰＯＰ", [2, 7, 10, None]),
    "HELLO to DREAM":  SongData(220, "HELLO to DREAM", "WACCA Lily", "アニメ／ＰＯＰ", [1, 6, 9.7, None]),
    "マッチョアネーム？":  SongData(221, "マッチョアネーム？", "WACCA Lily", "アニメ／ＰＯＰ", [2, 6, 12.7, None]),
    "お願いマッスル":  SongData(222, "お願いマッスル", "WACCA Lily", "アニメ／ＰＯＰ", [1, 7.7, 10.7, None]),
    "夢見る空へ":  SongData(223, "夢見る空へ", "WACCA Lily", "アニメ／ＰＯＰ", [2, 7.7, 11, None]),
    "NEXT COLOR PLANET":  SongData(224, "NEXT COLOR PLANET", "WACCA Lily", "アニメ／ＰＯＰ", [2, 7, 12, None]),
    "Say!ファンファーレ!":  SongData(225, "Say!ファンファーレ!", "WACCA Lily", "アニメ／ＰＯＰ", [3, 8, 12, None]),
    "ぺこみこ大戦争！！":  SongData(226, "ぺこみこ大戦争！！", "WACCA Lily", "アニメ／ＰＯＰ", [4, 8, 11, 13, None]),
    "Stasis feat.motoko -WACCA EDiT-":  SongData(227, "Stasis feat.motoko -WACCA EDiT-", "WACCA Lily", "TANO*C", [4, 7.7, 12.7, None]),
    "RAV#GIRL":  SongData(228, "RAV#GIRL", "WACCA Lily", "TANO*C", [3, 7.7, 12, None]),
    "KALACAKLA":  SongData(229, "KALACAKLA", "WACCA Lily", "TANO*C", [4, 8, 12.7, None]),
    "パニックポップ☆フェスティバル!!!":  SongData(230, "パニックポップ☆フェスティバル!!!", "WACCA Lily", "TANO*C（オリジナル）", [5, 10, 13, None]),
    "グルーヴ・ザ・ハート":  SongData(231, "グルーヴ・ザ・ハート", "WACCA Lily", "バラエティ", [4, 8, 12, None]),
    "Good Night, Bad Luck.":  SongData(232, "Good Night, Bad Luck.", "WACCA Lily", "バラエティ", [5, 10.7, 13.7, None]),
    "Got more raves?":  SongData(233, "Got more raves?", "WACCA Lily", "バラエティ", [6, 10.7, 13, None]),
    "QiXiN MAdN3ss 2153":  SongData(234, "QiXiN MAdN3ss 2153", "WACCA Lily", "オリジナル", [6, 11, 13.7, None]),
    "Fish Fight!":  SongData(235, "Fish Fight!", "WACCA Lily", "バラエティ", [4, 9, 11, None]),
    "シャカリキ・ファイト・ブンブン":  SongData(236, "シャカリキ・ファイト・ブンブン", "WACCA Lily", "2.5次元", [3, 6.7, 11.7, None]),
    "THERAPY":  SongData(237, "THERAPY", "WACCA Lily", "バラエティ", [4, 9, 12.7, None]),
    "恋メタル":  SongData(238, "恋メタル", "WACCA Lily", "TANO*C", [3, 8.7, 12.7, None]),
    "はげしこの夜 -Psylent Crazy Night-":  SongData(239, "はげしこの夜 -Psylent Crazy Night-", "WACCA Lily", "TANO*C（オリジナル）", [4, 8.7, 13.7, None]),
    "隔絶≡タナトス":  SongData(240, "隔絶≡タナトス", "WACCA Lily", "ボカロ", [4, 8, 13, None]),
    "進捗どうですか！":  SongData(241, "進捗どうですか！", "WACCA Lily", "ボカロ", [3, 7, 12.7, None]),
    "ワールドイズマイン":  SongData(242, "ワールドイズマイン", "WACCA Lily", "ボカロ", [3, 8, 11, None]),
    "ぼくらの16bit戦争":  SongData(243, "ぼくらの16bit戦争", "WACCA Lily", "ボカロ", [4, 9, 13, None]),
    "TWISTSTEP":  SongData(244, "TWISTSTEP", "WACCA Lily", "バラエティ", [3, 8.7, 12.7, None]),
    "PRESS START!":  SongData(245, "PRESS START!", "WACCA Lily", "バラエティ", [4, 8.7, 12.7, None]),
    "From Zero feat. 利香":  SongData(246, "From Zero feat. 利香", "WACCA Lily", "バラエティ", [3, 7.7, 11.7, None]),
    "Future Cαndy":  SongData(247, "Future Cαndy", "WACCA Lily", "バラエティ", [3, 9, 12.7, None]),
    "Big Bang":  SongData(248, "Big Bang", "WACCA Lily", "TANO*C（オリジナル）", [7, 11, 14, None]),
    "Liberate":  SongData(249, "Liberate", "WACCA Lily", "TANO*C（オリジナル）", [4, 9, 13, None]),
    "Animosity":  SongData(250, "Animosity", "WACCA Lily", "TANO*C（オリジナル）", [6, 10.7, 13.7, None]),
    "猫娘":  SongData(251, "猫娘", "WACCA Lily", "オリジナル", [6, 10, 13.7, None]),
    "フリーフォール":  SongData(252, "フリーフォール", "WACCA Lily", "オリジナル", [4, 8.7, 12.7, None]),
    "DUAL BREAKER XX":  SongData(253, "DUAL BREAKER XX", "WACCA Lily R", "TANO*C（オリジナル）", [6, 10.7, 13.7, None]),
    "SHAKE!":  SongData(254, "SHAKE!", "WACCA Lily R", "TANO*C（オリジナル）", [4, 9, 12.7, None]),
    "LIN NE KRO NE feat. lasah":  SongData(255, "LIN NE KRO NE feat. lasah", "WACCA Lily R", "オリジナル", [4, 9, 13.7, None]),
    "Lhaksha":  SongData(256, "Lhaksha", "WACCA Lily R", "オリジナル", [3, 9, 12, None]),
    "Megaton Killer":  SongData(257, "Megaton Killer", "WACCA Lily R", "TANO*C", [5, 10, 13, None]),
    "ATAMA WARUI":  SongData(258, "ATAMA WARUI", "WACCA Lily R", "TANO*C", [5, 9, 12.7, None]),
    "進捗WARS feat．ビートまりお":  SongData(259, "進捗WARS feat．ビートまりお", "WACCA Lily R", "バラエティ", [3, 7, 11, None]),
    "MAGENTA POTION":  SongData(260, "MAGENTA POTION", "WACCA Lily R", "バラエティ", [4, 8, 12, None]),
    "Weg":  SongData(261, "Weg", "WACCA Lily R", "バラエティ", [3, 8, 12, None]),
    "Apocalypse":  SongData(262, "Apocalypse", "WACCA Lily R", "バラエティ", [2, 7, 12, None]),
    "Rainmaker":  SongData(263, "Rainmaker", "WACCA Lily R", "バラエティ", [4, 9.7, 13, None]),
    "You are the Miserable":  SongData(264, "You are the Miserable", "WACCA Lily R", "バラエティ", [3, 10, 13.7, None]),
    "Stasis":  SongData(265, "Stasis", "WACCA Lily R", "バラエティ", [3, 10, 13, None]),
    "ホイホイ☆幻想ホロイズム":  SongData(266, "ホイホイ☆幻想ホロイズム", "WACCA Lily R", "東方アレンジ", [3, 7.7, 12.7, None]),
    "Scream out!":  SongData(267, "Scream out!", "WACCA Lily R", "東方アレンジ", [4, 8, 12.7, None]),
    "六兆年と一夜物語":  SongData(268, "六兆年と一夜物語", "WACCA Lily R", "ボカロ", [4, 8.7, 12, None]),
    "サクリファイス":  SongData(269, "サクリファイス", "WACCA Lily R", "アニメ／ＰＯＰ", [3, 9, 12, None]),
    "sister's noise":  SongData(270, "sister's noise", "WACCA Lily R", "アニメ／ＰＯＰ", [2, 6, 10, None]),
    "なだめスかし Negotiation":  SongData(271, "なだめスかし Negotiation", "WACCA Lily R", "アニメ／ＰＯＰ", [3, 7.7, 11.7, None]),
    "非実在系女子たちはどうすりゃいいですか？":  SongData(272, "非実在系女子たちはどうすりゃいいですか？", "WACCA Lily R", "アニメ／ＰＯＰ", [3, 8, 12, None]),
    "だれかの心臓になれたなら":  SongData(273, "だれかの心臓になれたなら", "WACCA Lily R", "ボカロ", [3, 7.7, 12, None]),
    "テレキャスタービーボーイ":  SongData(274, "テレキャスタービーボーイ", "WACCA Lily R", "ボカロ", [3, 8.7, 11.7, None]),
    "フィクサー":  SongData(275, "フィクサー", "WACCA Lily R", "ボカロ", [3, 7, 12.7, None]),
    "バレリーコ":  SongData(276, "バレリーコ", "WACCA Lily R", "ボカロ", [3, 8, 11, None]),
    "患部で止まってすぐ溶ける ～ 狂気の優曇華院":  SongData(277, "患部で止まってすぐ溶ける ～ 狂気の優曇華院", "WACCA Lily R", "東方アレンジ", [3, 9.7, 13, None]),
    "物凄い勢いでけーねが物凄いうた":  SongData(278, "物凄い勢いでけーねが物凄いうた", "WACCA Lily R", "東方アレンジ", [4, 9.7, 12, None]),
    "PUPA":  SongData(279, "PUPA", "WACCA Lily R", "バラエティ", [4, 8, 13.7, None]),
    "もぺもぺ":  SongData(280, "もぺもぺ", "WACCA Lily R", "バラエティ", [4, 8, 12.7, None]),
    "Destr0yer":  SongData(281, "Destr0yer", "WACCA Lily R", "バラエティ", [5, 8.7, 13, None]),
    "Popping Happiness!":  SongData(282, "Popping Happiness!", "WACCA Lily R", "TANO*C", [4, 8, 12, None]),
    "TRICKL4SH 220":  SongData(283, "TRICKL4SH 220", "WACCA Lily R", "TANO*C", [4, 10.7, 13.7, None]),
    "Madwing":  SongData(284, "Madwing", "WACCA Lily R", "TANO*C", [5, 9.7, 12.7, None]),
    "Destructive Little Sister":  SongData(285, "Destructive Little Sister", "WACCA Lily R", "東方アレンジ", [5, 10.7, 13.7, None]),
    "ARROW RAIN feat.ayame":  SongData(286, "ARROW RAIN feat.ayame", "WACCA Lily R", "東方アレンジ", [5, 9, 12, None]),
    "四次元跳躍機関":  SongData(287, "四次元跳躍機関", "WACCA Lily R", "東方アレンジ", [2, 9, 12.7, None]),
    "チルノは覚醒サマーデイズ！":  SongData(288, "チルノは覚醒サマーデイズ！", "WACCA Lily R", "東方アレンジ", [3, 8, 12, None]),
    "エピクロスの虹はもう見えない":  SongData(289, "エピクロスの虹はもう見えない", "WACCA Lily R", "東方アレンジ", [3, 8, 11, None]),
    "Photon Melodies":  SongData(290, "Photon Melodies", "WACCA Lily R", "アニメ／ＰＯＰ", [3, 7.7, 11, None]),
    "電乱★カウントダウン":  SongData(291, "電乱★カウントダウン", "WACCA Lily R", "アニメ／ＰＯＰ", [4, 7.7, 12, None]),
    "Dig Delight!":  SongData(292, "Dig Delight!", "WACCA Lily R", "アニメ／ＰＯＰ", [3, 8, 11, None]),
    "ぐるぐるDJ TURN!!":  SongData(293, "ぐるぐるDJ TURN!!", "WACCA Lily R", "アニメ／ＰＯＰ", [4, 10, 12.7, None]),
    "LOVE!HUG!GROOVY!!":  SongData(294, "LOVE!HUG!GROOVY!!", "WACCA Lily R", "アニメ／ＰＯＰ", [4, 8.7, 12, 13, None]),
    "BSCS":  SongData(295, "BSCS", "WACCA Lily R", "TANO*C", [4, 8.7, 13, None]),
    "FLVSH OUT":  SongData(296, "FLVSH OUT", "WACCA Lily R", "TANO*C", [4, 9.7, 13, None]),
    "Traveller feat.moimoi":  SongData(297, "Traveller feat.moimoi", "WACCA Lily R", "TANO*C", [2, 8, 12, None]),
    "やけにインザレイン feat. 小林私":  SongData(298, "やけにインザレイン feat. 小林私", "WACCA Lily R", "TANO*C", [3, 10, 13, None]),
    "Purple Skies":  SongData(299, "Purple Skies", "WACCA Lily R", "オリジナル", [3, 8, 12, None]),
    "Cauliflower":  SongData(300, "Cauliflower", "WACCA Lily R", "オリジナル", [4, 8.7, 12.7, None]),
    "Night Club Junkie":  SongData(301, "Night Club Junkie", "WACCA Lily R", "バラエティ", [2, 6.7, 12, None]),
    "私はNo 1！":  SongData(302, "私はNo 1！", "WACCA Lily R", "アニメ／ＰＯＰ", [3, 8, 12, None]),
    "cœur":  SongData(303, "cœur", "WACCA Lily R", "アニメ／ＰＯＰ", [3, 8.7, 12.7, None]),
    "ソロモン・ナイト":  SongData(304, "ソロモン・ナイト", "WACCA Lily R", "アニメ／ＰＯＰ", [3, 7.7, 13, None]),
    "Silentphobia":  SongData(305, "Silentphobia", "WACCA Lily R", "TANO*C（オリジナル）", [4, 10, 13, 14, None]),
    "eden":  SongData(306, "eden", "WACCA Lily R", "TANO*C（オリジナル）", [4, 10, 13, 14, None]),
    "Lost Illusion":  SongData(307, "Lost Illusion", "WACCA Lily R", "オリジナル", [4, 10.7, 12.7, None]),
    "Eternal Ending":  SongData(308, "Eternal Ending", "WACCA Lily R", "TANO*C", [5, 10.7, 13, None]),
    "EVE":  SongData(309, "EVE", "WACCA Lily R", "TANO*C（オリジナル）", [4, 9, 13, None]),
    "さんさーら！":  SongData(310, "さんさーら！", "WACCA Lily R", "バラエティ", [2, 7.7, 12, None]),
    "Meta-Mysteria":  SongData(311, "Meta-Mysteria", "WACCA Reverse", "TANO*C（オリジナル）", [6, 11, 14, None]),
    "超MANJIラッシュ":  SongData(312, "超MANJIラッシュ", "WACCA Reverse", "TANO*C（オリジナル）", [5, 9.7, 13.7, None]),
    "Kira☆Kira☆Night":  SongData(313, "Kira☆Kira☆Night", "WACCA Reverse", "オリジナル", [5, 9, 12.7, None]),
    "YOG":  SongData(314, "YOG", "WACCA Reverse", "オリジナル", [4, 9.7, 13.7, None]),
    "Love Kills U":  SongData(315, "Love Kills U", "WACCA Reverse", "オリジナル", [4, 8, 12, None]),
    "Ouvertüre":  SongData(316, "Ouvertüre", "WACCA Reverse", "オリジナル", [3, 9, 13, 14, None]),
    "Datamania (tpz Overheat Remix)":  SongData(317, "Datamania (tpz Overheat Remix)", "WACCA Reverse", "TANO*C", [3, 7.7, 12, None]),
    "Machinery of Avoid":  SongData(318, "Machinery of Avoid", "WACCA Reverse", "TANO*C", [4, 8, 12.7, None]),
    "Let you DIVE! (nitro rmx)":  SongData(319, "Let you DIVE! (nitro rmx)", "WACCA Reverse", "バラエティ", [4, 8.7, 12.7, None]),
    "Sheriruth (Laur Remix)":  SongData(320, "Sheriruth (Laur Remix)", "WACCA Reverse", "バラエティ", [4, 10, 13, None]),
    "最強STRONGER":  SongData(321, "最強STRONGER", "WACCA Reverse", "バラエティ", [5, 10, 14, None]),
    "Arcahv":  SongData(322, "Arcahv", "WACCA Reverse", "バラエティ", [3, 10, 13, None]),
    "#1f1e33":  SongData(323, "#1f1e33", "WACCA Reverse", "バラエティ", [3, 10.7, 13.7, None]),
    "Avant Raze":  SongData(324, "Avant Raze", "WACCA Reverse", "バラエティ", [3, 8, 12, None]),
    "Crime Wave":  SongData(325, "Crime Wave", "WACCA Reverse", "東方アレンジ", [3, 8, 12.7, None]),
    "サマータイムレコード":  SongData(326, "サマータイムレコード", "WACCA Reverse", "ボカロ", [3, 7.7, 11.7, None]),
    "ダーリンダンス":  SongData(327, "ダーリンダンス", "WACCA Reverse", "ボカロ", [2, 8.7, 12.7, None]),
    "KING":  SongData(328, "KING", "WACCA Reverse", "ボカロ", [2, 8, 11, None]),
    "トリノコシティ":  SongData(329, "トリノコシティ", "WACCA Reverse", "ボカロ", [3, 7.7, 12, None]),
    "Fam☆Fam☆Time!":  SongData(330, "Fam☆Fam☆Time!", "WACCA Reverse", "アニメ／ＰＯＰ", [3, 8, 11.7, None]),
    "Fly to NEW WORLD":  SongData(331, "Fly to NEW WORLD", "WACCA Reverse", "アニメ／ＰＯＰ", [3, 8, 12, None]),
    "透明声彩":  SongData(332, "透明声彩", "WACCA Reverse", "アニメ／ＰＯＰ", [3, 7, 11.7, None]),
    "D3LTA QOMPLEX":  SongData(333, "D3LTA QOMPLEX", "WACCA Reverse", "TANO*C", [4, 9.7, 13, None]),
    "Chobit Flavor":  SongData(334, "Chobit Flavor", "WACCA Reverse", "TANO*C", [3, 9, 12, None]),
    "Break Through Myself feat. Risa Yuzuki":  SongData(335, "Break Through Myself feat. Risa Yuzuki", "WACCA Reverse", "TANO*C", [4, 10, 13, None]),
    "回レ！雪月花":  SongData(336, "回レ！雪月花", "WACCA Reverse", "アニメ／ＰＯＰ", [2, 8, 11, 13.7, None]),
    "青空のラプソディ":  SongData(337, "青空のラプソディ", "WACCA Reverse", "アニメ／ＰＯＰ", [2, 6.7, 9, 11, None]),
    "メニメニマニマニ":  SongData(338, "メニメニマニマニ", "WACCA Reverse", "アニメ／ＰＯＰ", [3, 7.7, 12, None]),
    "おねがいダーリン":  SongData(339, "おねがいダーリン", "WACCA Reverse", "ボカロ", [4, 9, 11, None]),
    "怪盗Fの台本（シナリオ）〜消えたダイヤの謎〜":  SongData(340, "怪盗Fの台本（シナリオ）〜消えたダイヤの謎〜", "WACCA Reverse", "ボカロ", [3, 9, 13.7, None]),
    "ちがう!!!":  SongData(341, "ちがう!!!", "WACCA Reverse", "ボカロ", [4, 9.7, 12, None]),
    "∞(2018Remake)":  SongData(342, "∞(2018Remake)", "WACCA Reverse", "ボカロ", [3, 8.7, 13.7, None]),
    "ワールズエンド・ダンスホール":  SongData(343, "ワールズエンド・ダンスホール", "WACCA Reverse", "ボカロ", [3, 8, 12, None]),
    "炉心融解":  SongData(344, "炉心融解", "WACCA Reverse", "ボカロ", [2, 8, 12, None]),
    "粉骨砕身カジノゥ":  SongData(345, "粉骨砕身カジノゥ", "WACCA Reverse", "バラエティ", [3, 8, 13, None]),
    "The 90's Decision":  SongData(346, "The 90's Decision", "WACCA Reverse", "バラエティ", [4, 9, 13, None]),
    "Lights of Muse":  SongData(347, "Lights of Muse", "WACCA Reverse", "バラエティ", [3, 9.7, 12, None]),
    "XODUS":  SongData(348, "XODUS", "WACCA Reverse", "バラエティ", [5, 11, 14, None]),
    "Comet Coaster":  SongData(349, "Comet Coaster", "WACCA Reverse", "バラエティ", [5, 9.7, 13, None]),
    "恋のMoonlight":  SongData(350, "恋のMoonlight", "WACCA Reverse", "バラエティ", [2, 8, 11.7, None]),
    "NightTheater":  SongData(351, "NightTheater", "WACCA Reverse", "バラエティ", [3, 10, 13, None]),
    "花たちに希望を":  SongData(352, "花たちに希望を", "WACCA Reverse", "バラエティ", [3, 9.7, 12, None]),
    "うっせぇわ":  SongData(353, "うっせぇわ", "WACCA Reverse", "アニメ／ＰＯＰ", [3, 9, 12, 13, None]),
    "叩ケ　叩ケ　手ェ叩ケ":  SongData(354, "叩ケ　叩ケ　手ェ叩ケ", "WACCA Reverse", "アニメ／ＰＯＰ", [2, 7, 12, 13.7, None]),
    "ヒトガタ":  SongData(355, "ヒトガタ", "WACCA Reverse", "アニメ／ＰＯＰ", [3, 9.7, 12, None]),
    "Dimension Hacker":  SongData(356, "Dimension Hacker", "WACCA Reverse", "TANO*C（オリジナル）", [4, 10.7, 13, 14, None]),
    "DANGEROOOOUS JUNGLE":  SongData(357, "DANGEROOOOUS JUNGLE", "WACCA Reverse", "TANO*C（オリジナル）", [3, 10, 13, 14, None]),
    "EPHMR":  SongData(358, "EPHMR", "WACCA Reverse", "TANO*C（オリジナル）", [4, 10.7, 13, 14, None]),
    "クリムゾン帝王":  SongData(359, "クリムゾン帝王", "WACCA Reverse", "TANO*C（オリジナル）", [8, 11.7, 13.7, 14, None]),
    "吉原ラメント":  SongData(360, "吉原ラメント", "WACCA Reverse", "ボカロ", [3, 8, 12, None]),
    "メルト":  SongData(361, "メルト", "WACCA Reverse", "ボカロ", [3, 8.7, 12, None]),
    "天樂":  SongData(362, "天樂", "WACCA Reverse", "ボカロ", [3, 8, 12.7, None]),
    "アゲナゲン":  SongData(363, "アゲナゲン", "WACCA Reverse", "バラエティ", [4, 10, 13, None]),
    "ファムファタール":  SongData(364, "ファムファタール", "WACCA Reverse", "バラエティ", [3, 8, 11, None]),
    "cloud Ⅸ":  SongData(365, "cloud Ⅸ", "WACCA Reverse", "オリジナル", [4, 10, 13, None]),
    "CENSORED!!":  SongData(366, "CENSORED!!", "WACCA Reverse", "東方アレンジ", [4, 8.7, 13, None]),
    "Grip & Break down !!":  SongData(367, "Grip & Break down !!", "WACCA Reverse", "東方アレンジ", [3, 8, 12, None]),
    "神":  SongData(368, "神", "WACCA Reverse", "オリジナル", [6, 10.7, 13.7, 14, None]),
    "Onigami":  SongData(369, "Onigami", "WACCA Reverse", "TANO*C", [4, 9, 13, None]),
    "Candy Star":  SongData(370, "Candy Star", "WACCA Reverse", "TANO*C", [3, 9, 13, None]),
    "Invisible Frenzy (Camellia's '593: Insanely Fluctuated' Remix)":  SongData(371, "Invisible Frenzy (Camellia's '593: Insanely Fluctuated' Remix)", "WACCA Reverse", "TANO*C", [6, 11, 14, None]),
    "GENOCIDER (Kobaryo's FTN-Remix)":  SongData(372, "GENOCIDER (Kobaryo's FTN-Remix)", "WACCA Reverse", "TANO*C", [6, 10.7, 14, None]),
    "Möbius":  SongData(373, "Möbius", "WACCA Reverse", "TANO*C（オリジナル）", [8, 10.7, 14, 15, None]),
    "You & DIE":  SongData(374, "You & DIE", "WACCA Reverse", "TANO*C", [4, 10.7, 13, None]),
    "Reach My Voice":  SongData(375, "Reach My Voice", "WACCA Reverse", "TANO*C", [3, 8.7, 12.7, None]),
    "Ready Go feat. Yukacco":  SongData(376, "Ready Go feat. Yukacco", "WACCA Reverse", "TANO*C", [3, 8, 12, None]),
    "Big Daddy":  SongData(377, "Big Daddy", "WACCA Reverse", "TANO*C", [5, 8.7, 13, None]),
    "N3XTAGE":  SongData(378, "N3XTAGE", "WACCA Reverse", "TANO*C", [4, 10, 12.7, None]),
    "NIGHTWAVE FRAGMENTS":  SongData(379, "NIGHTWAVE FRAGMENTS", "WACCA Reverse", "TANO*C", [4, 10, 13.7, None]),
    "GAKKY":  SongData(380, "GAKKY", "WACCA Reverse", "TANO*C", [4, 10.7, 13.7, None]),
    "SUPER EMULATOR":  SongData(381, "SUPER EMULATOR", "WACCA Reverse", "TANO*C", [4, 11, 14, None]),
    "Brand New World feat. Yukacco":  SongData(382, "Brand New World feat. Yukacco", "WACCA Reverse", "TANO*C", [3, 7, 11.7, None]),
    "T+ VS SHARK":  SongData(383, "T+ VS SHARK", "WACCA Reverse", "TANO*C", [4, 10.7, 13.7, None]),
    "えくすとりーむ↑↑おんがくスクール feat. ななひら":  SongData(384, "えくすとりーむ↑↑おんがくスクール feat. ななひら", "WACCA Reverse", "TANO*C", [4, 10.7, 13.7, None]),
    "Avenue":  SongData(385, "Avenue", "WACCA Reverse", "TANO*C", [3, 7.7, 12.7, None]),
    "Middle":  SongData(386, "Middle", "WACCA Reverse", "TANO*C", [3, 7, 12.7, None]),
    "Obtain An Unused Whale In The Abstract Sea":  SongData(387, "Obtain An Unused Whale In The Abstract Sea", "WACCA Reverse", "TANO*C", [2, 6, 13, None]),
    "EXTRA HARD":  SongData(388, "EXTRA HARD", "WACCA Reverse", "TANO*C", [4, 11, 14, None]),
    "Odin":  SongData(389, "Odin", "WACCA Reverse", "TANO*C", [4, 10.7, 13, None]),
    "Viyella's Nightmare":  SongData(390, "Viyella's Nightmare", "WACCA Reverse", "TANO*C", [4, 11, 13.7, None]),
    "1BPM":  SongData(391, "1BPM", "WACCA Reverse", "TANO*C", [4, 10, 13.7, None]),
    "BPM=RT":  SongData(392, "BPM=RT", "WACCA Reverse", "TANO*C", [5, 10.7, 13.7, None]),
    "最先端坊将軍３":  SongData(393, "最先端坊将軍３", "WACCA Reverse", "TANO*C", [3, 8.7, 13.7, None]),
    "We are the Massive New Krew (2020Edit)":  SongData(394, "We are the Massive New Krew (2020Edit)", "WACCA Reverse", "TANO*C", [3, 8, 13, 14, None]),
    "To the sky -wacca edit- feat.motoko":  SongData(395, "To the sky -wacca edit- feat.motoko", "WACCA Reverse", "TANO*C", [3, 8.7, 12, None]),
    "Keep on Groovin' feat. mow*2":  SongData(396, "Keep on Groovin' feat. mow*2", "WACCA Reverse", "TANO*C", [4, 9.7, 12, None]),
    "Crush Out":  SongData(397, "Crush Out", "WACCA Reverse", "TANO*C", [4, 10, 12.7, None]),
    "Everybody Say HARDCORE TANO*C":  SongData(398, "Everybody Say HARDCORE TANO*C", "WACCA Reverse", "TANO*C", [4, 9, 13, None]),
    "Scramble TANO*C":  SongData(399, "Scramble TANO*C", "WACCA Reverse", "TANO*C", [3, 9.7, 12.7, None]),
    "DIVE with Ü":  SongData(400, "DIVE with Ü", "WACCA Reverse", "オリジナル", [3, 9, 13, 12, None]),
}

groups = {
    "WACCA": {name for name, data, in SONG_DATA.items() if data.version == "WACCA"},
    "WACCA S": {name for name, data, in SONG_DATA.items() if data.version == "WACCA S"},
    "WACCA Lily": {name for name, data, in SONG_DATA.items() if data.version == "WACCA Lily"},
    "WACCA Lily R": {name for name, data, in SONG_DATA.items() if data.version == "WACCA Lily R"},
    "WACCA Reverse": {name for name, data, in SONG_DATA.items() if data.version == "WACCA Reverse"},
    "アニメ／ＰＯＰ": {name for name, data, in SONG_DATA.items() if data.category == "アニメ／ＰＯＰ"},
    "ボカロ": {name for name, data, in SONG_DATA.items() if data.category == "ボカロ"},
    "東方アレンジ": {name for name, data, in SONG_DATA.items() if data.category == "東方アレンジ"},
    "2.5次元": {name for name, data, in SONG_DATA.items() if data.category == "2.5次元"},
    "バラエティ": {name for name, data, in SONG_DATA.items() if data.category == "バラエティ"},
    "オリジナル": {name for name, data, in SONG_DATA.items() if data.category == "オリジナル"},
    "TANO*C": {name for name, data, in SONG_DATA.items() if data.category == "TANO*C"},
    "TANO*C（オリジナル）": {name for name, data, in SONG_DATA.items() if data.category == "TANO*C（オリジナル）"},
}