from typing import Dict
from ..items import SongData

SONG_DATA: Dict[str, SongData] = {
    "Rainbow Dream":  SongData(10, "Rainbow Dream", "WACCA", "TANO*C（オリジナル）", [3, 8.7, 11.4, None]),
    "Knight Rider":  SongData(11, "Knight Rider", "WACCA", "TANO*C（オリジナル）", [6, 10.9, 13.3, None]),
    "Poseidon":  SongData(12, "Poseidon", "WACCA", "TANO*C（オリジナル）", [5, 9.9, 13.8, None]),
    "PARALLEL★PRISM":  SongData(13, "PARALLEL★PRISM", "WACCA", "TANO*C（オリジナル）", [3, 7.7, 10.8, 13.7, None]),
    "千本桜":  SongData(14, "千本桜", "WACCA", "ボカロ", [2, 7.9, 10.4, None]),
    "シュガーソングとビターステップ":  SongData(15, "シュガーソングとビターステップ", "WACCA", "アニメ／ＰＯＰ", [2, 7, 10.4, None]),
    "ピースサイン":  SongData(16, "ピースサイン", "WACCA", "アニメ／ＰＯＰ", [2, 6.9, 9.8, None]),
    "Singin'☆Shine！":  SongData(17, "Singin'☆Shine！", "WACCA", "2.5次元", [1, 5.3, 9.6, None]),
    "MEMORiZE":  SongData(18, "MEMORiZE", "WACCA", "TANO*C", [3, 8.1, 10, None]),
    "illanai-assorted":  SongData(19, "illanai-assorted", "WACCA", "TANO*C", [4, 8.9, 12.9, None]),
    "ファティマ":  SongData(20, "ファティマ", "WACCA", "アニメ／ＰＯＰ", [2, 6.8, 9.5, None]),
    "Soldiers":  SongData(21, "Soldiers", "WACCA", "TANO*C", [4, 8.8, 11.9, None]),
    "Fight for the CORE feat. Daisuke":  SongData(22, "Fight for the CORE feat. Daisuke", "WACCA", "TANO*C", [4, 10.7, 12.6, None]),
    "回レ！雪月花":  SongData(23, "回レ！雪月花", "WACCA", "アニメ／ＰＯＰ", [2, 8, 11, 13.8, None]),
    "エイリアンエイリアン":  SongData(24, "エイリアンエイリアン", "WACCA", "ボカロ", [2, 6.7, 10.5, None]),
    "砂の惑星 feat. 初音ミク":  SongData(25, "砂の惑星 feat. 初音ミク", "WACCA", "ボカロ", [3, 8.7, 10.5, None]),
    "マトリョシカ":  SongData(26, "マトリョシカ", "WACCA", "ボカロ", [3, 8.2, 10.4, 13.8, None]),
    "Let you DIVE!":  SongData(27, "Let you DIVE!", "WACCA", "オリジナル", [3, 9.7, 11.8, 13.4, None]),
    "かくしん的☆めたまるふぉ～ぜっ!":  SongData(28, "かくしん的☆めたまるふぉ～ぜっ!", "WACCA", "アニメ／ＰＯＰ", [1, 5.2, 9.5, None]),
    "徒花ネクロマンシー":  SongData(29, "徒花ネクロマンシー", "WACCA", "アニメ／ＰＯＰ", [3, 6.9, 9.7, None]),
    "POP TEAM EPIC":  SongData(30, "POP TEAM EPIC", "WACCA", "アニメ／ＰＯＰ", [3, 7.8, 11.4, None]),
    "ようこそジャパリパークへ":  SongData(31, "ようこそジャパリパークへ", "WACCA", "アニメ／ＰＯＰ", [2, 7.6, 10.7, None]),
    "ロキ":  SongData(32, "ロキ", "WACCA", "ボカロ", [4, 9.4, 11.6, None]),
    "ウマーベラス":  SongData(33, "ウマーベラス", "WACCA", "アニメ／ＰＯＰ", [1, 6.8, 9.8, None]),
    "ギミチョコ!!":  SongData(34, "ギミチョコ!!", "WACCA", "アニメ／ＰＯＰ", [4, 10.3, 12.9, None]),
    "ウミユリ海底譚":  SongData(35, "ウミユリ海底譚", "WACCA", "ボカロ", [1, 7.1, 10.2, 12.9, None]),
    "Seyana. ～何でも言うことを聞いてくれるアカネチャン～":  SongData(36, "Seyana. ～何でも言うことを聞いてくれるアカネチャン～", "WACCA", "ボカロ", [2, 9.3, 11.7, None]),
    "フラジール":  SongData(37, "フラジール", "WACCA", "ボカロ", [1, 7, 10.3, None]),
    "EZ DO DANCE -K.O.P. REMIX-":  SongData(38, "EZ DO DANCE -K.O.P. REMIX-", "WACCA", "アニメ／ＰＯＰ", [1, 6, 9.1, None]),
    "ルーンファクトリー４スペシャルより「この想いを乗せて」":  SongData(39, "ルーンファクトリー４スペシャルより「この想いを乗せて」", "WACCA", "バラエティ", [1, 5.6, 9, None]),
    "LEVATEiN feat. 野宮あゆみ":  SongData(40, "LEVATEiN feat. 野宮あゆみ", "WACCA", "TANO*C（オリジナル）", [4, 9.1, 12.5, None]),
    "BIG HEAD BANGING":  SongData(41, "BIG HEAD BANGING", "WACCA", "TANO*C（オリジナル）", [6, 11, 13.8, None]),
    "Quon":  SongData(42, "Quon", "WACCA", "TANO*C（オリジナル）", [5, 10.6, 12.8, 13.9, None]),
    "HELL FLAME":  SongData(43, "HELL FLAME", "WACCA", "TANO*C（オリジナル）", [5, 10.4, 12.7, 13.9, None]),
    "Gate One":  SongData(44, "Gate One", "WACCA", "TANO*C（オリジナル）", [4, 9.5, 12, None]),
    "Are You Ready":  SongData(45, "Are You Ready", "WACCA", "TANO*C（オリジナル）", [4, 10.1, 12.5, None]),
    "Over My Hand":  SongData(46, "Over My Hand", "WACCA", "TANO*C（オリジナル）", [3, 9.2, 11.1, None]),
    "Sunshine":  SongData(47, "Sunshine", "WACCA", "TANO*C", [4, 8.2, 11.3, None]),
    "Try again":  SongData(48, "Try again", "WACCA", "TANO*C", [4, 8.8, 10.6, None]),
    "Ever Free(Raw Edit)":  SongData(49, "Ever Free(Raw Edit)", "WACCA", "TANO*C", [3, 8.3, 10.1, None]),
    "BOOM! BOOM!! BOOM!!!":  SongData(50, "BOOM! BOOM!! BOOM!!!", "WACCA", "TANO*C", [4, 10.6, 12.3, None]),
    "BLUE SKY feat. 野宮あゆみ":  SongData(51, "BLUE SKY feat. 野宮あゆみ", "WACCA", "TANO*C", [3, 7.6, 10.4, None]),
    "Sound Chimera":  SongData(52, "Sound Chimera", "WACCA", "TANO*C", [5, 10.8, 12.8, 13.9, None]),
    "Nameless Story":  SongData(53, "Nameless Story", "WACCA", "アニメ／ＰＯＰ", [3, 7.5, 10.3, None]),
    "TOMORROW":  SongData(54, "TOMORROW", "WACCA", "アニメ／ＰＯＰ", [3, 8, 10.4, None]),
    "五等分の気持ち":  SongData(55, "五等分の気持ち", "WACCA", "アニメ／ＰＯＰ", [2, 6.1, 9.9, None]),
    "ゲームオーバー (feat. TORIENA)":  SongData(56, "ゲームオーバー (feat. TORIENA)", "WACCA", "バラエティ", [2, 7.7, 11.7, None]),
    "ファッとして桃源郷":  SongData(57, "ファッとして桃源郷", "WACCA", "アニメ／ＰＯＰ", [3, 9.3, 12, None]),
    "乙女解剖":  SongData(58, "乙女解剖", "WACCA", "ボカロ", [3, 7.3, 9.2, None]),
    "スクランブル交際":  SongData(59, "スクランブル交際", "WACCA", "ボカロ", [3, 8.4, 11, None]),
    "Shining Harmony":  SongData(60, "Shining Harmony", "WACCA", "TANO*C", [4, 9.6, 12.2, None]),
    "Jingle":  SongData(61, "Jingle", "WACCA", "TANO*C", [4, 9.7, 11.3, None]),
    "GRiDGALAXY":  SongData(62, "GRiDGALAXY", "WACCA", "TANO*C", [4, 8.3, 11.5, 13.3, None]),
    "conflict":  SongData(63, "conflict", "WACCA", "バラエティ", [5, 10.3, 13.4, None]),
    "BATTLE NO.1":  SongData(64, "BATTLE NO.1", "WACCA", "TANO*C", [6, 10.5, 13.7, 14.3, None]),
    "こんにちは、ARuFaです。":  SongData(65, "こんにちは、ARuFaです。", "WACCA", "バラエティ", [3, 7.5, 10.4, None]),
    "ぼくの夢、メチャクソ無限湧き":  SongData(66, "ぼくの夢、メチャクソ無限湧き", "WACCA", "バラエティ", [4, 9.6, 12.6, 13.8, None]),
    "EXCITE":  SongData(67, "EXCITE", "WACCA", "アニメ／ＰＯＰ", [1, 6.5, 10, None]),
    "Exitium":  SongData(68, "Exitium", "WACCA", "TANO*C（オリジナル）", [6, 11, 14.2, None]),
    "Blaze":  SongData(69, "Blaze", "WACCA", "TANO*C", [3, 8.7, 11.7, None]),
    "幸せになれる隠しコマンドがあるらしい":  SongData(70, "幸せになれる隠しコマンドがあるらしい", "WACCA", "ボカロ", [5, 10.5, 13.3, 0, None]),
    "ATARAX1A":  SongData(71, "ATARAX1A", "WACCA", "TANO*C（オリジナル）", [4, 8.6, 12.5, 13.7, None]),
    "13 Donkeys":  SongData(72, "13 Donkeys", "WACCA", "TANO*C（オリジナル）", [2, 8.4, 12.2, None]),
    "ADAM":  SongData(73, "ADAM", "WACCA", "TANO*C（オリジナル）", [5, 10.2, 13.4, None]),
    "HiGHER":  SongData(74, "HiGHER", "WACCA", "TANO*C", [3, 8.5, 12.2, 13.7, None]),
    "Source of Creation":  SongData(75, "Source of Creation", "WACCA", "TANO*C", [3, 8.1, 11.3, None]),
    "気まぐれメルシィ feat. 初音ミク":  SongData(76, "気まぐれメルシィ feat. 初音ミク", "WACCA", "ボカロ", [3, 7.4, 10.5, None]),
    "太陽系デスコ":  SongData(77, "太陽系デスコ", "WACCA", "ボカロ", [2, 7.4, 10.7, None]),
    "アカリがやってきたぞっ":  SongData(78, "アカリがやってきたぞっ", "WACCA", "ボカロ", [3, 8.5, 11.2, None]),
    "Akareram":  SongData(79, "Akareram", "WACCA", "TANO*C", [3, 8.5, 11.7, None]),
    "Galaxy Friends":  SongData(80, "Galaxy Friends", "WACCA", "TANO*C", [4, 8.9, 12.7, 13.9, None]),
    "Bad Apple!! feat. nomico":  SongData(81, "Bad Apple!! feat. nomico", "WACCA", "東方アレンジ", [1, 5.5, 9.3, 12.5, None]),
    "ナイト・オブ・ナイツ":  SongData(82, "ナイト・オブ・ナイツ", "WACCA", "東方アレンジ", [3, 9, 12, None]),
    "WARNING×WARNING×WARNING":  SongData(83, "WARNING×WARNING×WARNING", "WACCA", "東方アレンジ", [3, 7.7, 11.5, None]),
    "Raise Your Heart!!":  SongData(84, "Raise Your Heart!!", "WACCA", "アニメ／ＰＯＰ", [3, 7.4, 10.6, None]),
    "SHINY DAYS":  SongData(85, "SHINY DAYS", "WACCA", "アニメ／ＰＯＰ", [1, 5.2, 9, None]),
    "集結の華々":  SongData(86, "集結の華々", "WACCA", "バラエティ", [2, 6.3, 10.9, None]),
    "チルノのパーフェクトさんすう教室":  SongData(87, "チルノのパーフェクトさんすう教室", "WACCA", "東方アレンジ", [3, 9.2, 11.5, None]),
    "taboo tears you up 2017":  SongData(88, "taboo tears you up 2017", "WACCA", "東方アレンジ", [4, 9.8, 12.4, None]),
    "待チ人ハ来ズ。":  SongData(89, "待チ人ハ来ズ。", "WACCA", "東方アレンジ", [2, 6.4, 10.5, None]),
    "Chariot":  SongData(90, "Chariot", "WACCA", "TANO*C（オリジナル）", [3, 8.6, 12.4, 13.8, None]),
    "The Light":  SongData(91, "The Light", "WACCA", "アニメ／ＰＯＰ", [3, 7.8, 12.1, None]),
    "AIAIAI (feat. 中田ヤスタカ)":  SongData(92, "AIAIAI (feat. 中田ヤスタカ)", "WACCA", "アニメ／ＰＯＰ", [1, 6.4, 9.4, None]),
    "Hello, Morning":  SongData(93, "Hello, Morning", "WACCA", "アニメ／ＰＯＰ", [2, 7.1, 11.2, None]),
    "ただ君に晴れ":  SongData(94, "ただ君に晴れ", "WACCA", "アニメ／ＰＯＰ", [3, 7, 9.6, None]),
    "VOX Diamond":  SongData(95, "VOX Diamond", "WACCA", "TANO*C", [4, 7.9, 12.6, None]),
    "残酷な天使のテーゼ":  SongData(96, "残酷な天使のテーゼ", "WACCA", "アニメ／ＰＯＰ", [1, 5.3, 9.3, None]),
    "Pixel Galaxy":  SongData(97, "Pixel Galaxy", "WACCA", "バラエティ", [2, 7.2, 10.8, None]),
    "Utopia feat. shully":  SongData(98, "Utopia feat. shully", "WACCA", "オリジナル", [5, 9.4, 12.6, 13.7, None]),
    "You Only Live Once":  SongData(99, "You Only Live Once", "WACCA", "アニメ／ＰＯＰ", [1, 5.4, 9.1, None]),
    "にめんせい☆ウラオモテライフ!":  SongData(100, "にめんせい☆ウラオモテライフ!", "WACCA", "アニメ／ＰＯＰ", [3, 7.8, 10.5, None]),
    "劣等上等":  SongData(101, "劣等上等", "WACCA", "ボカロ", [3, 8, 11.9, 13.7, None]),
    "Stratoliner":  SongData(102, "Stratoliner", "WACCA", "オリジナル", [4, 9.8, 12.8, 13.8, None]),
    "Honey Panic!":  SongData(103, "Honey Panic!", "WACCA", "バラエティ", [3, 9.4, 12.1, None]),
    "初音ミクの消失":  SongData(104, "初音ミクの消失", "WACCA", "ボカロ", [5, 10.6, 13.8, None]),
    "Invisible Frenzy":  SongData(105, "Invisible Frenzy", "WACCA", "TANO*C（オリジナル）", [7, 11, 14.2, None]),
    "FREEDOM DiVE↓":  SongData(106, "FREEDOM DiVE↓", "WACCA", "バラエティ", [6, 10.9, 13.9, None]),
    "Jägermeister":  SongData(107, "Jägermeister", "WACCA", "バラエティ", [3, 8.8, 11.2, None]),
    "『エキセントリック少年ボウイ』のテーマ":  SongData(108, "『エキセントリック少年ボウイ』のテーマ", "WACCA", "バラエティ", [1, 5.7, 12.6, None]),
    "What's this?":  SongData(109, "What's this?", "WACCA", "バラエティ", [3, 6.3, 10.2, None]),
    "JINGLE DEATH":  SongData(110, "JINGLE DEATH", "WACCA", "TANO*C（オリジナル）", [4, 10.4, 13.2, None]),
    "Over the sweat and tears":  SongData(111, "Over the sweat and tears", "WACCA", "2.5次元", [1, 5.6, 9.4, None]),
    "jacaranda":  SongData(112, "jacaranda", "WACCA", "オリジナル", [4, 9.3, 12.7, None]),
    "CHECKER FLAG":  SongData(113, "CHECKER FLAG", "WACCA", "オリジナル", [3, 7.2, 12.9, None]),
    "BLVST BEVT":  SongData(114, "BLVST BEVT", "WACCA", "TANO*C", [4, 10, 12.6, None]),
    "only my railgun":  SongData(115, "only my railgun", "WACCA S", "アニメ／ＰＯＰ", [3, 6.7, 9.5, None]),
    "ゴーストルール":  SongData(116, "ゴーストルール", "WACCA S", "ボカロ", [3, 9, 11.6, None]),
    "Shiny Memory feat.Yukacco":  SongData(117, "Shiny Memory feat.Yukacco", "WACCA S", "TANO*C", [3, 9.8, 12.5, None]),
    "オドループ":  SongData(118, "オドループ", "WACCA S", "アニメ／ＰＯＰ", [3, 7.9, 10.4, None]),
    "燐廻":  SongData(119, "燐廻", "WACCA S", "バラエティ", [2, 7.7, 11.1, None]),
    "ロストワンの号哭":  SongData(120, "ロストワンの号哭", "WACCA S", "ボカロ", [4, 8.3, 12.2, None]),
    "いーあるふぁんくらぶ":  SongData(121, "いーあるふぁんくらぶ", "WACCA S", "ボカロ", [2, 6.5, 10, None]),
    "悪戯センセーション":  SongData(122, "悪戯センセーション", "WACCA S", "東方アレンジ", [2, 8.6, 12.3, None]),
    "Mami Mami Zone":  SongData(123, "Mami Mami Zone", "WACCA S", "東方アレンジ", [4, 9.2, 11.4, None]),
    "Demon's Rave":  SongData(124, "Demon's Rave", "WACCA S", "オリジナル", [5, 10, 12.8, None]),
    "Murasaki":  SongData(125, "Murasaki", "WACCA S", "TANO*C（オリジナル）", [3, 7.5, 12.4, None]),
    "Mazy Metroplex":  SongData(126, "Mazy Metroplex", "WACCA S", "TANO*C（オリジナル）", [4, 10.8, 13.7, None]),
    "ドラマツルギー":  SongData(127, "ドラマツルギー", "WACCA S", "アニメ／ＰＯＰ", [2, 7.4, 10.1, None]),
    "ナイト・オブ・ナイツ (かめりあ’s“ワンス・アポン・ア・ナイト”Remix)":  SongData(128, "ナイト・オブ・ナイツ (かめりあ’s“ワンス・アポン・ア・ナイト”Remix)", "WACCA S", "東方アレンジ", [5, 10.5, 13.1, None]),
    "†DOOF†SENC†":  SongData(129, "†DOOF†SENC†", "WACCA S", "TANO*C", [6, 10.4, 13.6, None]),
    "LOSE CONTROL":  SongData(130, "LOSE CONTROL", "WACCA S", "TANO*C", [3, 8.1, 11.3, None]),
    "ベースラインやってる？笑":  SongData(131, "ベースラインやってる？笑", "WACCA S", "バラエティ", [4, 9.9, 12.2, None]),
    "EU over Progress":  SongData(132, "EU over Progress", "WACCA S", "バラエティ", [6, 10.7, 12.7, None]),
    "シャルル":  SongData(133, "シャルル", "WACCA S", "アニメ／ＰＯＰ", [3, 7.1, 10.3, None]),
    "Shiny Smily Story":  SongData(134, "Shiny Smily Story", "WACCA S", "アニメ／ＰＯＰ", [3, 6.5, 10.4, None]),
    "Dream☆Story":  SongData(135, "Dream☆Story", "WACCA S", "アニメ／ＰＯＰ", [2, 7.5, 11.2, None]),
    "without U":  SongData(136, "without U", "WACCA S", "アニメ／ＰＯＰ", [3, 7.2, 10.2, None]),
    "新宝島":  SongData(137, "新宝島", "WACCA S", "アニメ／ＰＯＰ", [1, 6.3, 9.4, None]),
    "U.S.A.":  SongData(138, "U.S.A.", "WACCA S", "アニメ／ＰＯＰ", [2, 7.1, 10.2, None]),
    "セツナトリップ":  SongData(139, "セツナトリップ", "WACCA S", "ボカロ", [3, 9, 12.1, None]),
    "カゲロウデイズ":  SongData(140, "カゲロウデイズ", "WACCA S", "ボカロ", [4, 9.5, 11.3, None]),
    "天ノ弱":  SongData(141, "天ノ弱", "WACCA S", "ボカロ", [3, 7.3, 10.1, None]),
    "ケロ⑨Destiny":  SongData(142, "ケロ⑨Destiny", "WACCA S", "東方アレンジ", [2, 6.2, 11.7, None]),
    "LOVE EAST":  SongData(143, "LOVE EAST", "WACCA S", "東方アレンジ", [3, 7.3, 11, None]),
    "天狗の落とし文 feat. ytr":  SongData(144, "天狗の落とし文 feat. ytr", "WACCA S", "東方アレンジ", [3, 8.2, 12.1, None]),
    "神寂":  SongData(145, "神寂", "WACCA S", "東方アレンジ", [4, 10.8, 13.5, None]),
    "風に乗せた願い":  SongData(146, "風に乗せた願い", "WACCA S", "東方アレンジ", [3, 7.1, 10.3, None]),
    "GASHATT":  SongData(147, "GASHATT", "WACCA S", "オリジナル", [4, 10.1, 12.4, None]),
    "Strange Bar":  SongData(148, "Strange Bar", "WACCA S", "TANO*C", [3, 10.2, 12.8, None]),
    "輪廻転生":  SongData(149, "輪廻転生", "WACCA S", "アニメ／ＰＯＰ", [3, 9.2, 12.3, None]),
    "ストライク・ザ・ブラッド":  SongData(150, "ストライク・ザ・ブラッド", "WACCA S", "アニメ／ＰＯＰ", [3, 8.7, 11.7, None]),
    "Eyes on me feat. Such":  SongData(151, "Eyes on me feat. Such", "WACCA S", "バラエティ", [3, 7.7, 12.4, None]),
    "GOODWORLD":  SongData(152, "GOODWORLD", "WACCA S", "バラエティ", [2, 9.1, 12.6, None]),
    "Altale":  SongData(153, "Altale", "WACCA S", "バラエティ", [4, 9.3, 12.3, None]),
    "君のStarlight Road":  SongData(154, "君のStarlight Road", "WACCA S", "バラエティ", [3, 8.2, 10.3, None]),
    "FUJIN Rumble":  SongData(155, "FUJIN Rumble", "WACCA S", "バラエティ", [5, 10.8, 13.6, None]),
    "聖者の鼓動":  SongData(156, "聖者の鼓動", "WACCA S", "バラエティ", [2, 7.6, 12.4, None]),
    "BUCHiGiRE Berserker":  SongData(157, "BUCHiGiRE Berserker", "WACCA S", "バラエティ", [4, 10.9, 13.9, None]),
    "Brain Power":  SongData(158, "Brain Power", "WACCA S", "バラエティ", [4, 9.7, 13, None]),
    "Ultra Red":  SongData(159, "Ultra Red", "WACCA S", "TANO*C", [3, 9.6, 12.8, None]),
    "サイクルヒット":  SongData(160, "サイクルヒット", "WACCA S", "TANO*C", [5, 10.5, 13.5, None]),
    "ガンガン・ドンドン":  SongData(161, "ガンガン・ドンドン", "WACCA S", "2.5次元", [2, 6, 9.7, None]),
    "スマイル・アンド・ティアズ":  SongData(162, "スマイル・アンド・ティアズ", "WACCA S", "2.5次元", [2, 6.1, 9.5, None]),
    "STILL HOT IN MY HEART":  SongData(163, "STILL HOT IN MY HEART", "WACCA S", "2.5次元", [3, 7.3, 10.3, None]),
    "ぼなぺてぃーと♡S":  SongData(164, "ぼなぺてぃーと♡S", "WACCA S", "アニメ／ＰＯＰ", [2, 7.7, 11.5, None]),
    "デタラメなマイナスとプラスにおけるブレンド考":  SongData(165, "デタラメなマイナスとプラスにおけるブレンド考", "WACCA S", "アニメ／ＰＯＰ", [2, 5.7, 10, None]),
    "リアル初音ミクの消失":  SongData(166, "リアル初音ミクの消失", "WACCA S", "ボカロ", [6, 10.2, 13.7, None]),
    "チュルリラ・チュルリラ・ダッダッダ！":  SongData(167, "チュルリラ・チュルリラ・ダッダッダ！", "WACCA S", "ボカロ", [4, 8.3, 12.4, None]),
    "おばけのウケねらい":  SongData(168, "おばけのウケねらい", "WACCA S", "ボカロ", [3, 8, 11.7, None]),
    "ベノム":  SongData(169, "ベノム", "WACCA S", "ボカロ", [3, 7.5, 12.1, None]),
    "Metamorphose":  SongData(170, "Metamorphose", "WACCA S", "TANO*C（オリジナル）", [4, 10.3, 12.7, 13.9, None]),
    "MAGiC4LG1RL M3GA S7R1KE!":  SongData(171, "MAGiC4LG1RL M3GA S7R1KE!", "WACCA S", "TANO*C（オリジナル）", [4, 10, 13.1, None]),
    "METEOR BURST":  SongData(172, "METEOR BURST", "WACCA S", "TANO*C（オリジナル）", [5, 10.9, 13.8, None]),
    "XTREME":  SongData(173, "XTREME", "WACCA S", "TANO*C（オリジナル）", [6, 11, 12.9, 14, None]),
    "天使光輪":  SongData(174, "天使光輪", "WACCA S", "TANO*C（オリジナル）", [7, 11, 13.2, 14.1, None]),
    "ツアー・ファイナル":  SongData(175, "ツアー・ファイナル", "WACCA S", "TANO*C", [3, 9.4, 12.3, None]),
    "青空のラプソディ":  SongData(176, "青空のラプソディ", "WACCA S", "アニメ／ＰＯＰ", [2, 6.8, 9.3, 11, None]),
    "ダダダダ天使":  SongData(177, "ダダダダ天使", "WACCA S", "アニメ／ＰＯＰ", [3, 7.8, 12, None]),
    "Bravely You":  SongData(178, "Bravely You", "WACCA S", "アニメ／ＰＯＰ", [1, 6.5, 9.5, None]),
    "ダンシング☆サムライ":  SongData(179, "ダンシング☆サムライ", "WACCA S", "バラエティ", [3, 7.7, 10.5, None]),
    "WHITE":  SongData(180, "WHITE", "WACCA S", "バラエティ", [3, 8, 10.5, None]),
    "HOT LIMIT":  SongData(181, "HOT LIMIT", "LILY", "アニメ／ＰＯＰ", [3, 7.9, 10, None]),
    "ないものねだり":  SongData(182, "ないものねだり", "LILY", "アニメ／ＰＯＰ", [2, 7.7, 11.1, None]),
    "While Shining feat.Yukacco":  SongData(183, "While Shining feat.Yukacco", "LILY", "TANO*C", [3, 8.6, 12.3, None]),
    "ブリキノダンス":  SongData(184, "ブリキノダンス", "LILY", "ボカロ", [3, 7.9, 12.3, None]),
    "LETHAL;WEAPON":  SongData(185, "LETHAL;WEAPON", "LILY", "オリジナル", [3, 8, 12.9, 13.9, None]),
    "RAGE OF DUST":  SongData(186, "RAGE OF DUST", "LILY", "アニメ／ＰＯＰ", [3, 8.4, 9.6, None]),
    "秒針を噛む":  SongData(187, "秒針を噛む", "LILY", "アニメ／ＰＯＰ", [2, 6.8, 11, None]),
    "ガヴリールドロップキック":  SongData(188, "ガヴリールドロップキック", "LILY", "アニメ／ＰＯＰ", [3, 6.9, 11, None]),
    "This game":  SongData(189, "This game", "LILY", "アニメ／ＰＯＰ", [2, 7.6, 10.7, None]),
    "ポジティブ☆ダンスタイム":  SongData(190, "ポジティブ☆ダンスタイム", "LILY", "ボカロ", [3, 8.9, 11.6, None]),
    "Gimme×Gimme feat. 初音ミク・鏡音リン":  SongData(191, "Gimme×Gimme feat. 初音ミク・鏡音リン", "LILY", "ボカロ", [2, 8.1, 12, None]),
    "39みゅーじっく！":  SongData(192, "39みゅーじっく！", "LILY", "ボカロ", [2, 7.4, 10.9, None]),
    "ゆけむり魂温泉 II":  SongData(193, "ゆけむり魂温泉 II", "LILY", "東方アレンジ", [3, 7.5, 12, None]),
    "明星ロケット":  SongData(194, "明星ロケット", "LILY", "東方アレンジ", [2, 7.5, 11.7, None]),
    "Calamity Fortune":  SongData(195, "Calamity Fortune", "LILY", "東方アレンジ", [4, 10, 13.7, None]),
    "インドア系ならトラックメイカー":  SongData(196, "インドア系ならトラックメイカー", "LILY", "バラエティ", [2, 7.5, 12.9, None]),
    "with U":  SongData(197, "with U", "LILY", "オリジナル", [3, 7.9, 11.8, 13.6, None]),
    "Tell Me":  SongData(198, "Tell Me", "LILY", "オリジナル", [3, 7.9, 11.8, 13.9, None]),
    "THE MUZZLE FACING":  SongData(199, "THE MUZZLE FACING", "LILY", "オリジナル", [4, 9.8, 13.8, None]),
    "SUPER REACTOR":  SongData(200, "SUPER REACTOR", "LILY", "TANO*C（オリジナル）", [4, 8.2, 13, None]),
    "ONOMATO Pairing!!!":  SongData(201, "ONOMATO Pairing!!!", "LILY", "TANO*C（オリジナル）", [2, 8.5, 12.4, None]),
    "GENOCIDER":  SongData(202, "GENOCIDER", "LILY", "TANO*C（オリジナル）", [6, 11, 14.1, None]),
    "ALiVE":  SongData(203, "ALiVE", "LILY", "TANO*C", [3, 7.8, 11, None]),
    "キラメキライダー☆":  SongData(204, "キラメキライダー☆", "LILY", "アニメ／ＰＯＰ", [2, 7, 11.5, None]),
    "キラッとスタート (USAO Remix)":  SongData(205, "キラッとスタート (USAO Remix)", "LILY", "アニメ／ＰＯＰ", [4, 8.2, 12.5, None]),
    "Make it！ (DJ Genki Remix)":  SongData(206, "Make it！ (DJ Genki Remix)", "LILY", "アニメ／ＰＯＰ", [3, 7.8, 11.6, None]),
    "ハート♥イロ♥トリドリ〜ム":  SongData(207, "ハート♥イロ♥トリドリ〜ム", "LILY", "アニメ／ＰＯＰ", [1, 6, 10.1, None]),
    "Make it！":  SongData(208, "Make it！", "LILY", "アニメ／ＰＯＰ", [1, 5.1, 9.4, None]),
    "キラッとスタート":  SongData(209, "キラッとスタート", "LILY", "アニメ／ＰＯＰ", [2, 7.4, 10.2, None]),
    "ニュー・ウェーブ":  SongData(210, "ニュー・ウェーブ", "LILY", "2.5次元", [2, 6.1, 9.3, None]),
    "アスノヨゾラ哨戒班":  SongData(211, "アスノヨゾラ哨戒班", "LILY", "ボカロ", [3, 7.6, 11.9, None]),
    "ヒビカセ":  SongData(212, "ヒビカセ", "LILY", "ボカロ", [3, 8.4, 12.3, None]),
    "脳漿炸裂ガール":  SongData(213, "脳漿炸裂ガール", "LILY", "ボカロ", [5, 9.5, 13.5, None]),
    "Grayed Out-Antifront-":  SongData(214, "Grayed Out-Antifront-", "LILY", "バラエティ", [3, 9.6, 13.2, None]),
    "ARTEMiS":  SongData(215, "ARTEMiS", "LILY", "オリジナル", [4, 10.6, 13.9, None]),
    "Poppin' Shower":  SongData(216, "Poppin' Shower", "LILY", "TANO*C", [3, 9.8, 12.5, 13.5, None]),
    "進捗どうですか？":  SongData(217, "進捗どうですか？", "LILY", "東方アレンジ", [3, 8.6, 12.5, None]),
    "Sweet Requiem":  SongData(218, "Sweet Requiem", "LILY", "東方アレンジ", [3, 9.2, 12.7, None]),
    "Help me, ERINNNNNN!!":  SongData(219, "Help me, ERINNNNNN!!", "LILY", "東方アレンジ", [3, 7.7, 11.6, None]),
    "HELLO to DREAM":  SongData(220, "HELLO to DREAM", "LILY", "アニメ／ＰＯＰ", [1, 6.5, 9.7, None]),
    "over and over":  SongData(221, "over and over", "LILY", "アニメ／ＰＯＰ", [2, 7.5, 10.4, None]),
    "トロピカッ☆バケーション":  SongData(222, "トロピカッ☆バケーション", "LILY", "アニメ／ＰＯＰ", [2, 7.5, 10.7, None]),
    "お願いマッスル":  SongData(223, "お願いマッスル", "LILY", "アニメ／ＰＯＰ", [1, 7.7, 10.7, None]),
    "マッチョアネーム？":  SongData(224, "マッチョアネーム？", "LILY", "アニメ／ＰＯＰ", [2, 6.6, 12.7, None]),
    "ぺこみこ大戦争！！":  SongData(225, "ぺこみこ大戦争！！", "LILY", "アニメ／ＰＯＰ", [4, 8.4, 11.2, 13.2, None]),
    "Say!ファンファーレ!":  SongData(226, "Say!ファンファーレ!", "LILY", "アニメ／ＰＯＰ", [3, 8.6, 12.5, None]),
    "夢見る空へ":  SongData(227, "夢見る空へ", "LILY", "アニメ／ＰＯＰ", [2, 7.7, 11.3, None]),
    "NEXT COLOR PLANET":  SongData(228, "NEXT COLOR PLANET", "LILY", "アニメ／ＰＯＰ", [2, 7.5, 12.6, None]),
    "パニックポップ☆フェスティバル!!!":  SongData(229, "パニックポップ☆フェスティバル!!!", "LILY", "TANO*C（オリジナル）", [5, 10, 13.3, None]),
    "Stasis feat.motoko -WACCA EDiT-":  SongData(230, "Stasis feat.motoko -WACCA EDiT-", "LILY", "TANO*C", [4, 7.9, 12.7, None]),
    "RAV#GIRL":  SongData(231, "RAV#GIRL", "LILY", "TANO*C", [3, 7.8, 12.6, None]),
    "KALACAKLA":  SongData(232, "KALACAKLA", "LILY", "TANO*C", [4, 8, 12.7, None]),
    "Good Night, Bad Luck.":  SongData(233, "Good Night, Bad Luck.", "LILY", "バラエティ", [5, 10.7, 13.7, None]),
    "Got more raves?":  SongData(234, "Got more raves?", "LILY", "バラエティ", [6, 10.9, 13.5, None]),
    "グルーヴ・ザ・ハート":  SongData(235, "グルーヴ・ザ・ハート", "LILY", "バラエティ", [4, 8.5, 12.5, None]),
    "QiXiN MAdN3ss 2153":  SongData(236, "QiXiN MAdN3ss 2153", "LILY", "オリジナル", [6, 11, 13.9, None]),
    "恋メタル":  SongData(237, "恋メタル", "LILY", "TANO*C", [3, 8.8, 12.7, None]),
    "Fish Fight!":  SongData(238, "Fish Fight!", "LILY", "バラエティ", [4, 9, 11.6, None]),
    "THERAPY":  SongData(239, "THERAPY", "LILY", "バラエティ", [4, 9.1, 12.7, None]),
    "はげしこの夜 -Psylent Crazy Night-":  SongData(240, "はげしこの夜 -Psylent Crazy Night-", "LILY", "TANO*C（オリジナル）", [4, 8.8, 13.7, None]),
    "シャカリキ・ファイト・ブンブン":  SongData(241, "シャカリキ・ファイト・ブンブン", "LILY", "2.5次元", [3, 6.7, 11.7, None]),
    "進捗どうですか！":  SongData(242, "進捗どうですか！", "LILY", "ボカロ", [3, 7.3, 12.8, None]),
    "ワールドイズマイン":  SongData(243, "ワールドイズマイン", "LILY", "ボカロ", [3, 8.3, 11.6, None]),
    "ぼくらの16bit戦争":  SongData(244, "ぼくらの16bit戦争", "LILY", "ボカロ", [4, 9.1, 13.4, None]),
    "隔絶≡タナトス":  SongData(245, "隔絶≡タナトス", "LILY", "ボカロ", [4, 8.5, 13.5, None]),
    "From Zero feat. 利香":  SongData(246, "From Zero feat. 利香", "LILY", "バラエティ", [3, 7.7, 11.8, None]),
    "PRESS START!":  SongData(247, "PRESS START!", "LILY", "バラエティ", [4, 8.7, 12.7, None]),
    "TWISTSTEP":  SongData(248, "TWISTSTEP", "LILY", "バラエティ", [3, 8.8, 12.7, None]),
    "Future Cαndy":  SongData(249, "Future Cαndy", "LILY", "バラエティ", [3, 9.1, 12.7, None]),
    "猫娘":  SongData(250, "猫娘", "LILY", "オリジナル", [6, 10.6, 13.7, None]),
    "フリーフォール":  SongData(251, "フリーフォール", "LILY", "オリジナル", [4, 8.8, 12.7, 13.8, None]),
    "Liberate":  SongData(252, "Liberate", "LILY", "TANO*C（オリジナル）", [4, 9.5, 13.1, None]),
    "Animosity":  SongData(253, "Animosity", "LILY", "TANO*C（オリジナル）", [6, 10.9, 13.8, None]),
    "Big Bang":  SongData(254, "Big Bang", "LILY", "TANO*C（オリジナル）", [7, 11, 14.2, None]),
    "六兆年と一夜物語":  SongData(255, "六兆年と一夜物語", "LILY R", "ボカロ", [4, 8.9, 12.5, None]),
    "サクリファイス":  SongData(256, "サクリファイス", "LILY R", "アニメ／ＰＯＰ", [3, 9.1, 12.2, None]),
    "進捗WARS feat．ビートまりお":  SongData(257, "進捗WARS feat．ビートまりお", "LILY R", "バラエティ", [3, 7, 11.5, None]),
    "sister's noise":  SongData(258, "sister's noise", "LILY R", "アニメ／ＰＯＰ", [2, 6, 10.1, None]),
    "Weg":  SongData(259, "Weg", "LILY R", "バラエティ", [3, 8.6, 12.3, None]),
    "Apocalypse":  SongData(260, "Apocalypse", "LILY R", "バラエティ", [2, 7.6, 12.4, None]),
    "Rainmaker":  SongData(261, "Rainmaker", "LILY R", "バラエティ", [4, 9.9, 13.5, None]),
    "You are the Miserable":  SongData(262, "You are the Miserable", "LILY R", "バラエティ", [3, 10, 13.9, None]),
    "Stasis":  SongData(263, "Stasis", "LILY R", "バラエティ", [3, 10.2, 13.6, None]),
    "ホイホイ☆幻想ホロイズム":  SongData(264, "ホイホイ☆幻想ホロイズム", "LILY R", "東方アレンジ", [3, 7.7, 12.7, None]),
    "なだめスかし Negotiation":  SongData(265, "なだめスかし Negotiation", "LILY R", "アニメ／ＰＯＰ", [3, 7.7, 11.9, None]),
    "非実在系女子たちはどうすりゃいいですか？":  SongData(266, "非実在系女子たちはどうすりゃいいですか？", "LILY R", "アニメ／ＰＯＰ", [3, 8.5, 12.6, None]),
    "Scream out!":  SongData(267, "Scream out!", "LILY R", "東方アレンジ", [4, 8.1, 12.8, None]),
    "MAGENTA POTION":  SongData(268, "MAGENTA POTION", "LILY R", "バラエティ", [4, 8.1, 12.6, None]),
    "Megaton Killer":  SongData(269, "Megaton Killer", "LILY R", "TANO*C", [5, 10, 13.6, None]),
    "ATAMA WARUI":  SongData(270, "ATAMA WARUI", "LILY R", "TANO*C", [5, 9.1, 12.9, 14.2, None]),
    "LIN NE KRO NE feat. lasah":  SongData(271, "LIN NE KRO NE feat. lasah", "LILY R", "オリジナル", [4, 9, 13.7, None]),
    "Lhaksha":  SongData(272, "Lhaksha", "LILY R", "オリジナル", [3, 9.6, 12.5, None]),
    "SHAKE!":  SongData(273, "SHAKE!", "LILY R", "TANO*C（オリジナル）", [4, 9.5, 12.7, None]),
    "DUAL BREAKER XX":  SongData(274, "DUAL BREAKER XX", "LILY R", "TANO*C（オリジナル）", [6, 10.8, 13.8, None]),
    "テレキャスタービーボーイ":  SongData(275, "テレキャスタービーボーイ", "LILY R", "ボカロ", [3, 8.9, 11.9, None]),
    "バレリーコ":  SongData(276, "バレリーコ", "LILY R", "ボカロ", [3, 8.2, 11.6, None]),
    "フィクサー":  SongData(277, "フィクサー", "LILY R", "ボカロ", [3, 7.3, 12.9, None]),
    "だれかの心臓になれたなら":  SongData(278, "だれかの心臓になれたなら", "LILY R", "ボカロ", [3, 7.8, 12.1, None]),
    "患部で止まってすぐ溶ける ～ 狂気の優曇華院":  SongData(279, "患部で止まってすぐ溶ける ～ 狂気の優曇華院", "LILY R", "東方アレンジ", [3, 9.8, 13.2, None]),
    "物凄い勢いでけーねが物凄いうた":  SongData(280, "物凄い勢いでけーねが物凄いうた", "LILY R", "東方アレンジ", [4, 9.9, 12.2, None]),
    "PUPA":  SongData(281, "PUPA", "LILY R", "バラエティ", [4, 8.6, 13.7, None]),
    "Destr0yer":  SongData(282, "Destr0yer", "LILY R", "バラエティ", [5, 8.7, 13, None]),
    "もぺもぺ":  SongData(283, "もぺもぺ", "LILY R", "バラエティ", [4, 8.2, 12.7, None]),
    "Popping Happiness!":  SongData(284, "Popping Happiness!", "LILY R", "TANO*C", [4, 8.5, 12.4, None]),
    "Madwing":  SongData(285, "Madwing", "LILY R", "TANO*C", [5, 9.9, 12.8, None]),
    "TRICKL4SH 220":  SongData(286, "TRICKL4SH 220", "LILY R", "TANO*C", [4, 10.9, 13.8, None]),
    "チルノは覚醒サマーデイズ！":  SongData(287, "チルノは覚醒サマーデイズ！", "LILY R", "東方アレンジ", [3, 8.6, 12.3, None]),
    "エピクロスの虹はもう見えない":  SongData(288, "エピクロスの虹はもう見えない", "LILY R", "東方アレンジ", [3, 8.4, 11.3, None]),
    "ARROW RAIN feat.ayame":  SongData(289, "ARROW RAIN feat.ayame", "LILY R", "東方アレンジ", [5, 9.2, 12.6, None]),
    "四次元跳躍機関":  SongData(290, "四次元跳躍機関", "LILY R", "東方アレンジ", [2, 9.1, 12.7, None]),
    "Destructive Little Sister":  SongData(291, "Destructive Little Sister", "LILY R", "東方アレンジ", [5, 10.9, 13.9, None]),
    "LOVE!HUG!GROOVY!!":  SongData(292, "LOVE!HUG!GROOVY!!", "LILY R", "アニメ／ＰＯＰ", [4, 8.7, 12.4, 13.5, None]),
    "Dig Delight!":  SongData(293, "Dig Delight!", "LILY R", "アニメ／ＰＯＰ", [3, 8.3, 11.4, None]),
    "電乱★カウントダウン":  SongData(294, "電乱★カウントダウン", "LILY R", "アニメ／ＰＯＰ", [4, 7.8, 12.5, None]),
    "Photon Melodies":  SongData(295, "Photon Melodies", "LILY R", "アニメ／ＰＯＰ", [3, 7.7, 11.5, None]),
    "ぐるぐるDJ TURN!!":  SongData(296, "ぐるぐるDJ TURN!!", "LILY R", "アニメ／ＰＯＰ", [4, 10.1, 12.8, None]),
    "やけにインザレイン feat. 小林私":  SongData(297, "やけにインザレイン feat. 小林私", "LILY R", "TANO*C", [3, 10.3, 13.1, None]),
    "Traveller feat.moimoi":  SongData(298, "Traveller feat.moimoi", "LILY R", "TANO*C", [2, 8.4, 12.4, None]),
    "FLVSH OUT":  SongData(299, "FLVSH OUT", "LILY R", "TANO*C", [4, 9.8, 13.5, None]),
    "BSCS":  SongData(300, "BSCS", "LILY R", "TANO*C", [4, 8.8, 13.3, None]),
    "Night Club Junkie":  SongData(301, "Night Club Junkie", "LILY R", "バラエティ", [2, 6.8, 12.5, None]),
    "Cauliflower":  SongData(302, "Cauliflower", "LILY R", "オリジナル", [4, 8.7, 12.8, None]),
    "Purple Skies":  SongData(303, "Purple Skies", "LILY R", "オリジナル", [3, 8.4, 12.4, 13.8, None]),
    "ソロモン・ナイト":  SongData(304, "ソロモン・ナイト", "LILY R", "アニメ／ＰＯＰ", [3, 7.8, 13.4, None]),
    "cœur":  SongData(305, "cœur", "LILY R", "アニメ／ＰＯＰ", [3, 8.7, 12.7, None]),
    "私はNo 1！":  SongData(306, "私はNo 1！", "LILY R", "アニメ／ＰＯＰ", [3, 8.4, 12.3, None]),
    "EVE":  SongData(307, "EVE", "LILY R", "TANO*C（オリジナル）", [4, 9.2, 13.1, None]),
    "Lost Illusion":  SongData(308, "Lost Illusion", "LILY R", "オリジナル", [4, 10.7, 12.7, None]),
    "eden":  SongData(309, "eden", "LILY R", "TANO*C（オリジナル）", [4, 10.5, 13.3, 14.2, None]),
    "Silentphobia":  SongData(310, "Silentphobia", "LILY R", "TANO*C（オリジナル）", [4, 10.3, 13.6, 14, None]),
    "Eternal Ending":  SongData(311, "Eternal Ending", "LILY R", "TANO*C", [5, 10.9, 13.4, None]),
    "さんさーら！":  SongData(312, "さんさーら！", "LILY R", "バラエティ", [2, 7.9, 12.4, None]),
    "トリノコシティ":  SongData(313, "トリノコシティ", "REVERSE", "ボカロ", [3, 7.7, 12.2, None]),
    "Fam☆Fam☆Time!":  SongData(314, "Fam☆Fam☆Time!", "REVERSE", "アニメ／ＰＯＰ", [3, 8.2, 11.9, None]),
    "KING":  SongData(315, "KING", "REVERSE", "ボカロ", [2, 8, 11.6, None]),
    "ダーリンダンス":  SongData(316, "ダーリンダンス", "REVERSE", "ボカロ", [2, 8.7, 12.8, None]),
    "サマータイムレコード":  SongData(317, "サマータイムレコード", "REVERSE", "ボカロ", [3, 7.8, 11.9, None]),
    "Machinery of Avoid":  SongData(318, "Machinery of Avoid", "REVERSE", "TANO*C", [4, 8.5, 12.7, None]),
    "Datamania (tpz Overheat Remix)":  SongData(319, "Datamania (tpz Overheat Remix)", "REVERSE", "TANO*C", [3, 7.8, 12.6, None]),
    "Ouvertüre":  SongData(320, "Ouvertüre", "REVERSE", "オリジナル", [3, 9.6, 13.3, 14.2, None]),
    "Love Kills U":  SongData(321, "Love Kills U", "REVERSE", "オリジナル", [4, 8.4, 12.5, 13.8, None]),
    "超MANJIラッシュ":  SongData(322, "超MANJIラッシュ", "REVERSE", "TANO*C（オリジナル）", [5, 9.7, 13.7, None]),
    "YOG":  SongData(323, "YOG", "REVERSE", "オリジナル", [4, 9.7, 13.8, None]),
    "Meta-Mysteria":  SongData(324, "Meta-Mysteria", "REVERSE", "TANO*C（オリジナル）", [6, 11, 14.1, None]),
    "Avant Raze":  SongData(325, "Avant Raze", "REVERSE", "バラエティ", [3, 8, 12.6, None]),
    "#1f1e33":  SongData(326, "#1f1e33", "REVERSE", "バラエティ", [3, 10.9, 13.9, None]),
    "Arcahv":  SongData(327, "Arcahv", "REVERSE", "バラエティ", [3, 10.5, 13.6, None]),
    "最強STRONGER":  SongData(328, "最強STRONGER", "REVERSE", "バラエティ", [5, 10.6, 14, None]),
    "Sheriruth (Laur Remix)":  SongData(329, "Sheriruth (Laur Remix)", "REVERSE", "バラエティ", [4, 10.3, 13.3, None]),
    "Let you DIVE! (nitro rmx)":  SongData(330, "Let you DIVE! (nitro rmx)", "REVERSE", "バラエティ", [4, 8.7, 12.7, None]),
    "うっせぇわ":  SongData(331, "うっせぇわ", "REVERSE", "アニメ／ＰＯＰ", [3, 9.6, 12.2, 13.2, None]),
    "Kira☆Kira☆Night":  SongData(332, "Kira☆Kira☆Night", "REVERSE", "オリジナル", [5, 9.6, 12.9, None]),
    "Crime Wave":  SongData(333, "Crime Wave", "REVERSE", "東方アレンジ", [3, 8.1, 12.7, None]),
    "叩ケ　叩ケ　手ェ叩ケ":  SongData(334, "叩ケ　叩ケ　手ェ叩ケ", "REVERSE", "アニメ／ＰＯＰ", [2, 7.3, 12.3, 13.8, None]),
    "透明声彩":  SongData(335, "透明声彩", "REVERSE", "アニメ／ＰＯＰ", [3, 7.6, 11.8, None]),
    "Fly to NEW WORLD":  SongData(336, "Fly to NEW WORLD", "REVERSE", "アニメ／ＰＯＰ", [3, 8.3, 12.2, None]),
    "Break Through Myself feat. Risa Yuzuki":  SongData(337, "Break Through Myself feat. Risa Yuzuki", "REVERSE", "TANO*C", [4, 10.2, 13.4, None]),
    "Chobit Flavor":  SongData(338, "Chobit Flavor", "REVERSE", "TANO*C", [3, 9.2, 12.6, None]),
    "D3LTA QOMPLEX":  SongData(339, "D3LTA QOMPLEX", "REVERSE", "TANO*C", [4, 9.9, 13.1, None]),
    "メニメニマニマニ":  SongData(340, "メニメニマニマニ", "REVERSE", "アニメ／ＰＯＰ", [3, 7.8, 12.3, None]),
    "怪盗Fの台本（シナリオ）〜消えたダイヤの謎〜":  SongData(341, "怪盗Fの台本（シナリオ）〜消えたダイヤの謎〜", "REVERSE", "ボカロ", [3, 9.1, 13.7, None]),
    "おねがいダーリン":  SongData(342, "おねがいダーリン", "REVERSE", "ボカロ", [4, 9.3, 11.6, None]),
    "ちがう!!!":  SongData(343, "ちがう!!!", "REVERSE", "ボカロ", [4, 9.7, 12.4, None]),
    "ワールズエンド・ダンスホール":  SongData(344, "ワールズエンド・ダンスホール", "REVERSE", "ボカロ", [3, 8.6, 12.5, None]),
    "炉心融解":  SongData(345, "炉心融解", "REVERSE", "ボカロ", [2, 8.6, 12.2, None]),
    "∞(2018Remake)":  SongData(346, "∞(2018Remake)", "REVERSE", "ボカロ", [3, 8.7, 13.8, None]),
    "Lights of Muse":  SongData(347, "Lights of Muse", "REVERSE", "バラエティ", [3, 9.9, 12, None]),
    "粉骨砕身カジノゥ":  SongData(348, "粉骨砕身カジノゥ", "REVERSE", "バラエティ", [3, 8.1, 13.6, None]),
    "The 90's Decision":  SongData(349, "The 90's Decision", "REVERSE", "バラエティ", [4, 9.5, 13.5, None]),
    "XODUS":  SongData(350, "XODUS", "REVERSE", "バラエティ", [5, 11, 14.4, None]),
    "Comet Coaster":  SongData(351, "Comet Coaster", "REVERSE", "バラエティ", [5, 9.9, 13.3, None]),
    "恋のMoonlight":  SongData(352, "恋のMoonlight", "REVERSE", "バラエティ", [2, 8, 11.8, None]),
    "花たちに希望を":  SongData(353, "花たちに希望を", "REVERSE", "バラエティ", [3, 9.8, 12.4, None]),
    "NightTheater":  SongData(354, "NightTheater", "REVERSE", "バラエティ", [3, 10, 13, None]),
    "ヒトガタ":  SongData(355, "ヒトガタ", "REVERSE", "アニメ／ＰＯＰ", [3, 9.7, 12.6, None]),
    "DANGEROOOOUS JUNGLE":  SongData(356, "DANGEROOOOUS JUNGLE", "REVERSE", "TANO*C（オリジナル）", [3, 10.6, 13.4, 14.3, None]),
    "Dimension Hacker":  SongData(357, "Dimension Hacker", "REVERSE", "TANO*C（オリジナル）", [4, 10.8, 13.4, 14.3, None]),
    "EPHMR":  SongData(358, "EPHMR", "REVERSE", "TANO*C（オリジナル）", [4, 10.7, 13.2, 14.1, None]),
    "クリムゾン帝王":  SongData(359, "クリムゾン帝王", "REVERSE", "TANO*C（オリジナル）", [8, 11.7, 13.7, 14.5, None]),
    "メルト":  SongData(360, "メルト", "REVERSE", "ボカロ", [3, 8.7, 12.6, None]),
    "天樂":  SongData(361, "天樂", "REVERSE", "ボカロ", [3, 8.6, 12.7, None]),
    "吉原ラメント":  SongData(362, "吉原ラメント", "REVERSE", "ボカロ", [3, 8.3, 12.4, None]),
    "アゲナゲン":  SongData(363, "アゲナゲン", "REVERSE", "バラエティ", [4, 10.5, 13.5, None]),
    "ファムファタール":  SongData(364, "ファムファタール", "REVERSE", "バラエティ", [3, 8, 11.1, None]),
    "cloud IX":  SongData(365, "cloud IX", "REVERSE", "オリジナル", [4, 10.5, 13.6, None]),
    "Grip & Break down !!":  SongData(366, "Grip & Break down !!", "REVERSE", "東方アレンジ", [3, 8.5, 12, None]),
    "CENSORED!!":  SongData(367, "CENSORED!!", "REVERSE", "東方アレンジ", [4, 8.7, 13.4, None]),
    "神":  SongData(368, "神", "REVERSE", "オリジナル", [6, 10.9, 13.7, 14.4, None]),
    "Candy Star":  SongData(369, "Candy Star", "REVERSE", "TANO*C", [3, 9.5, 13.2, None]),
    "Onigami":  SongData(370, "Onigami", "REVERSE", "TANO*C", [4, 9, 13.2, None]),
    "Invisible Frenzy (Camellia's '593: Insanely Fluctuated' Remix)":  SongData(371, "Invisible Frenzy (Camellia's '593: Insanely Fluctuated' Remix)", "REVERSE", "TANO*C", [6, 11.2, 14.3, None]),
    "GENOCIDER (Kobaryo's FTN-Remix)":  SongData(372, "GENOCIDER (Kobaryo's FTN-Remix)", "REVERSE", "TANO*C", [6, 10.7, 14.3, None]),
    "Möbius":  SongData(373, "Möbius", "REVERSE", "TANO*C（オリジナル）", [8, 10.8, 14.4, 15.1, None]),
    "You & DIE":  SongData(374, "You & DIE", "REVERSE", "TANO*C", [4, 10.7, 13.6, None]),
    "Reach My Voice":  SongData(375, "Reach My Voice", "REVERSE", "TANO*C", [3, 8.8, 12.8, None]),
    "Ready Go feat. Yukacco":  SongData(376, "Ready Go feat. Yukacco", "REVERSE", "TANO*C", [3, 8.6, 12.3, None]),
    "Big Daddy":  SongData(377, "Big Daddy", "REVERSE", "TANO*C", [5, 8.7, 13.3, None]),
    "N3XTAGE":  SongData(378, "N3XTAGE", "REVERSE", "TANO*C", [4, 10.4, 12.7, 13.7, None]),
    "NIGHTWAVE FRAGMENTS":  SongData(379, "NIGHTWAVE FRAGMENTS", "REVERSE", "TANO*C", [4, 10.6, 13.7, None]),
    "GAKKY":  SongData(380, "GAKKY", "REVERSE", "TANO*C", [4, 10.7, 13.7, None]),
    "SUPER EMULATOR":  SongData(381, "SUPER EMULATOR", "REVERSE", "TANO*C", [4, 11, 14.3, None]),
    "Brand New World feat. Yukacco":  SongData(382, "Brand New World feat. Yukacco", "REVERSE", "TANO*C", [3, 7.5, 11.8, None]),
    "T+ VS SHARK":  SongData(383, "T+ VS SHARK", "REVERSE", "TANO*C", [4, 10.9, 13.8, None]),
    "えくすとりーむ↑↑おんがくスクール feat. ななひら":  SongData(384, "えくすとりーむ↑↑おんがくスクール feat. ななひら", "REVERSE", "TANO*C", [4, 10.9, 13.8, None]),
    "Avenue":  SongData(385, "Avenue", "REVERSE", "TANO*C", [3, 7.9, 12.9, None]),
    "Middle":  SongData(386, "Middle", "REVERSE", "TANO*C", [3, 7.6, 12.9, None]),
    "Obtain An Unused Whale In The Abstract Sea":  SongData(387, "Obtain An Unused Whale In The Abstract Sea", "REVERSE", "TANO*C", [2, 6, 13.3, None]),
    "EXTRA HARD":  SongData(388, "EXTRA HARD", "REVERSE", "TANO*C", [4, 11, 14.1, None]),
    "Odin":  SongData(389, "Odin", "REVERSE", "TANO*C", [4, 10.7, 13.6, None]),
    "Viyella's Nightmare":  SongData(390, "Viyella's Nightmare", "REVERSE", "TANO*C", [4, 11, 13.8, None]),
    "1BPM":  SongData(391, "1BPM", "REVERSE", "TANO*C", [4, 10.5, 13.7, None]),
    "BPM=RT":  SongData(392, "BPM=RT", "REVERSE", "TANO*C", [5, 10.8, 13.9, None]),
    "最先端坊将軍３":  SongData(393, "最先端坊将軍３", "REVERSE", "TANO*C", [3, 8.8, 13.8, None]),
    "We are the Massive New Krew (2020Edit)":  SongData(394, "We are the Massive New Krew (2020Edit)", "REVERSE", "TANO*C", [3, 8.6, 13, 14.1, None]),
    "To the sky -wacca edit- feat.motoko":  SongData(395, "To the sky -wacca edit- feat.motoko", "REVERSE", "TANO*C", [3, 8.9, 12.5, None]),
    "Keep on Groovin' feat. mow*2":  SongData(396, "Keep on Groovin' feat. mow*2", "REVERSE", "TANO*C", [4, 9.9, 12.5, None]),
    "Crush Out":  SongData(397, "Crush Out", "REVERSE", "TANO*C", [4, 10.2, 12.9, None]),
    "Everybody Say HARDCORE TANO*C":  SongData(398, "Everybody Say HARDCORE TANO*C", "REVERSE", "TANO*C", [4, 9.1, 13.4, None]),
    "Scramble TANO*C":  SongData(399, "Scramble TANO*C", "REVERSE", "TANO*C", [3, 9.6, 12.8, None]),
    "DIVE With Ü":  SongData(400, "DIVE With Ü", "REVERSE", "オリジナル", [3, 9.6, 13.3, 12, None]),
    "ぼくの夢、メチャクソ無限湧き (ななひら ver.)":  SongData(401, "ぼくの夢、メチャクソ無限湧き (ななひら ver.)", "PLUS", "バラエティ", [4, 10.7, 13.7, None]),
    "Blossom":  SongData(402, "Blossom", "PLUS", "バラエティ", [4, 9, 13.2, None]),
    "BULK UP (GAME EXCLUSIVE EDIT)":  SongData(403, "BULK UP (GAME EXCLUSIVE EDIT)", "PLUS", "バラエティ", [7, 10, 13.8, None]),
    "春を告げる":  SongData(404, "春を告げる", "PLUS", "アニメ／ＰＯＰ", [4, 7, 12.2, None]),
    "君のせい":  SongData(405, "君のせい", "PLUS", "アニメ／ＰＯＰ", [5, 8, 12.5, None]),
    "君のせい":  SongData(406, "君のせい", "PLUS", "アニメ／ＰＯＰ", [2, 7, 11.5, None]),
    "Chakra":  SongData(407, "Chakra", "PLUS", "バラエティ", [3, 9.3, 13.1, None]),
    "ÅMARA(大未来電脳)":  SongData(408, "ÅMARA(大未来電脳)", "PLUS", "ボカロ", [6, 9.7, 12.1, 13.9, None]),
    "caesura.":  SongData(409, "caesura.", "PLUS", "バラエティ", [7, 10.6, 13.5, 14.5, None]),
    "ラグトレイン":  SongData(410, "ラグトレイン", "PLUS", "ボカロ", [1, 8, 11.8, 13.2, None]),
    "Hainuwele":  SongData(411, "Hainuwele", "PLUS", "バラエティ", [7, 10.7, 13.9, None]),
    "Gestalt":  SongData(412, "Gestalt", "PLUS", "TANO*C", [5, 8.4, 12.7, None]),
    "Rebuff":  SongData(413, "Rebuff", "PLUS", "TANO*C", [6, 10.7, 13.7, None]),
    "Colors":  SongData(414, "Colors", "PLUS", "東方アレンジ", [4, 8.7, 11, None]),
    "Joe Fight":  SongData(415, "Joe Fight", "PLUS", "TANO*C", [5, 10.7, 14, None]),
    "ラビットホール":  SongData(416, "ラビットホール", "PLUS", "ボカロ", [4, 9.4, 13.3, None]),
    "Make Up Your World feat. キョンシーのCiちゃん & らっぷびと":  SongData(417, "Make Up Your World feat. キョンシーのCiちゃん & らっぷびと", "PLUS", "TANO*C", [4, 9.9, 12.6, None]),
    "Asteroid [feat. blaxervant]":  SongData(418, "Asteroid [feat. blaxervant]", "PLUS", "TANO*C", [4, 8, 12.5, None]),
    "B.B.K.K.B.K.K.":  SongData(419, "B.B.K.K.B.K.K.", "PLUS", "バラエティ", [3, 9, 13.1, 0, None]),
    "Caramelldansen (Speedycake Remix)":  SongData(420, "Caramelldansen (Speedycake Remix)", "PLUS", "アニメ／ＰＯＰ", [5, 9.7, 12.7, None]),
    "Cheatreal":  SongData(421, "Cheatreal", "PLUS", "TANO*C", [5, 10.7, 13.6, None]),
    "IMPULSE // WEAVER":  SongData(422, "IMPULSE // WEAVER", "PLUS", "オリジナル", [4, 8, 12.3, None]),
    "INTERNET YAMERO":  SongData(423, "INTERNET YAMERO", "PLUS", "バラエティ", [5, 9.9, 13.5, None]),
    "唱":  SongData(424, "唱", "PLUS", "バラエティ", [4, 8, 12.4, 13.4, None]),
    "Blows Up Everything":  SongData(425, "Blows Up Everything", "PLUS", "バラエティ", [4, 9, 13.7, None]),
    "Confessions of a Rotten Girl ft. Hatsune Miku":  SongData(426, "Confessions of a Rotten Girl ft. Hatsune Miku", "PLUS", "ボカロ", [4, 9, 13.2, None]),
    "Got It Bad":  SongData(427, "Got It Bad", "PLUS", "TANO*C", [7, 10.5, 14, None]),
    "強風オールバック (feat.歌愛ユキ)":  SongData(428, "強風オールバック (feat.歌愛ユキ)", "PLUS", "ボカロ", [2, 7, 11.9, 13.1, None]),
    "my flow":  SongData(429, "my flow", "PLUS", "バラエティ", [5, 8.7, 13.4, None]),
    "N3V3R G3T OV3R":  SongData(430, "N3V3R G3T OV3R", "PLUS", "バラエティ", [4, 10, 12.8, None]),
    "POWER OF UNITY":  SongData(431, "POWER OF UNITY", "PLUS", "バラエティ", [5, 10, 13.8, None]),
    "Straight into the lights":  SongData(432, "Straight into the lights", "PLUS", "バラエティ", [3, 9.7, 13.4, 14.2, None]),
    "Happy Synthesizer":  SongData(433, "Happy Synthesizer", "PLUS", "バラエティ", [3, 7, 10.7, 12.3, None]),
    "Latent Kingdom":  SongData(434, "Latent Kingdom", "PLUS", "バラエティ", [8, 11, 13.3, 14.3, None]),
    "�":  SongData(435, "�", "PLUS", "オリジナル", [8, 11.6, 14.3, 15, None]),
    "egoIST":  SongData(436, "egoIST", "PLUS", "オリジナル", [5, 9.8, 12.7, 14, None]),
    "ミラクルポップ☆アドベンチャー!!!!!":  SongData(437, "ミラクルポップ☆アドベンチャー!!!!!", "PLUS", "TANO*C", [5, 10, 13.7, None]),
    "How To Make 音ゲ~曲!":  SongData(438, "How To Make 音ゲ~曲!", "PLUS", "バラエティ", [5, 9, 13.5, None]),
    "Feels So Right feat. Renko":  SongData(439, "Feels So Right feat. Renko", "PLUS", "バラエティ", [4, 8.8, 10.6, 13.1, None]),
    "Distorted Fate":  SongData(440, "Distorted Fate", "PLUS", "バラエティ", [5, 9.8, 13.8, None]),
    "Rrhar'il":  SongData(441, "Rrhar'il", "PLUS", "バラエティ", [5, 8.9, 13.5, 14.2, None]),
    "Chronomia":  SongData(442, "Chronomia", "PLUS", "バラエティ", [6, 11, 13.7, None]),
    "Get Your Wish":  SongData(443, "Get Your Wish", "PLUS", "バラエティ", [3, 6.8, 10, None]),
    "Mãos para cima! ~手を上げな~":  SongData(444, "Mãos para cima! ~手を上げな~", "PLUS", "ボカロ", [3, 9, 12.8, None]),
    "Mujinku-Vacuum Track#ADD8E6-":  SongData(445, "Mujinku-Vacuum Track#ADD8E6-", "PLUS", "バラエティ", [4, 10, 13.9, None]),
    "Twisted Drop Party":  SongData(446, "Twisted Drop Party", "PLUS", "TANO*C", [4, 10.1, 13.1, None]),
    "惑星ループ":  SongData(447, "惑星ループ", "PLUS", "ボカロ", [4, 10.7, 12.7, None]),
    "DAWNBREAKER":  SongData(448, "DAWNBREAKER", "PLUS", "バラエティ", [5, 9.7, 12.3, None]),
    "ICEBURN":  SongData(449, "ICEBURN", "PLUS", "バラエティ", [4, 9.8, 13.8, None]),
    "Random Access Emotions":  SongData(450, "Random Access Emotions", "PLUS", "バラエティ", [3, 10, 12.2, 13.5, None]),
    "STARTLINER":  SongData(451, "STARTLINER", "PLUS", "バラエティ", [4, 8.7, 11.6, None]),
    "Stellar:Dream":  SongData(452, "Stellar:Dream", "PLUS", "バラエティ", [6, 10, 13.8, 14.2, None]),
    "Titania":  SongData(453, "Titania", "PLUS", "バラエティ", [5, 11, 13.7, 14.3, None]),
    "Y.Y.Y.計画!!!!":  SongData(454, "Y.Y.Y.計画!!!!", "PLUS", "バラエティ", [4, 8.8, 12.5, None]),
    "WakeUP MakeUP FEVER!":  SongData(455, "WakeUP MakeUP FEVER!", "PLUS", "バラエティ", [3, 8, 12.6, None]),
    "Last Kingdom":  SongData(456, "Last Kingdom", "PLUS", "バラエティ", [6, 10.5, 13.6, None]),
    "Good bye, Merry-Go-Round.":  SongData(457, "Good bye, Merry-Go-Round.", "PLUS", "バラエティ", [5, 10.8, 12.8, 14, None]),
    "Don't Fight The Music":  SongData(458, "Don't Fight The Music", "PLUS", "バラエティ", [6, 10.7, 13.4, 14.4, None]),
    "Pop Sequence":  SongData(459, "Pop Sequence", "PLUS", "バラエティ", [1, 5.7, 11.7, None]),
    "Crossing Delta":  SongData(460, "Crossing Delta", "PLUS", "バラエティ", [6, 10.8, 13.8, None]),
    "Paved Garden":  SongData(461, "Paved Garden", "PLUS", "バラエティ", [4, 8.3, 12.6, None]),
    "Shadow Bang":  SongData(462, "Shadow Bang", "PLUS", "TANO*C", [5, 10, 13.4, None]),
    "Slapstick Parfait":  SongData(463, "Slapstick Parfait", "PLUS", "バラエティ", [5, 9.9, 13.5, None]),
    "Kirakira Noel Story!!":  SongData(464, "Kirakira Noel Story!!", "PLUS", "バラエティ", [4, 8.9, 12.9, None]),
    "GIGA FLARE VIP":  SongData(465, "GIGA FLARE VIP", "PLUS", "バラエティ", [5, 10.8, 13.6, None]),
    "SWAG!!":  SongData(466, "SWAG!!", "PLUS", "バラエティ", [2, 9.7, 12.7, None]),
    "ビビデバ | BIBBIDIBA":  SongData(467, "ビビデバ | BIBBIDIBA", "PLUS", "アニメ／ＰＯＰ", [1, 6.5, 10.5, 13, None]),
    "Maholova":  SongData(468, "Maholova", "PLUS", "バラエティ", [4, 10.4, 13.3, None]),
    "MVURBD":  SongData(469, "MVURBD", "PLUS", "バラエティ", [6, 10.7, 14, None]),
    "Burned Out":  SongData(470, "Burned Out", "PLUS", "TANO*C", [4, 9.8, 13.6, None]),
    "MEGA TSKR":  SongData(471, "MEGA TSKR", "PLUS", "バラエティ", [4, 10.8, 13.9, None]),
    "The Rebellion of Phantom (feat. Valkyria)":  SongData(472, "The Rebellion of Phantom (feat. Valkyria)", "PLUS", "TANO*C", [5, 9.8, 13.2, None]),
    "sys_dei/cide":  SongData(473, "sys_dei/cide", "PLUS", "オリジナル", [7, 11.7, 14.3, 14.8, None]),
    "B2GFM":  SongData(474, "B2GFM", "PLUS", "TANO*C", [4, 8.9, 12.4, None]),
    "BATTLE NO.1 (DJ Myosuke Remix)":  SongData(475, "BATTLE NO.1 (DJ Myosuke Remix)", "PLUS", "TANO*C", [6, 11, 14.2, None]),
    "Drive Thrust":  SongData(476, "Drive Thrust", "PLUS", "バラエティ", [5, 10.9, 14, None]),
    "LUMIS:ETHER* feat.M1shamo & □□□□□□":  SongData(477, "LUMIS:ETHER* feat.M1shamo & □□□□□□", "PLUS", "TANO*C", [6, 10.8, 13.3, None]),
    "Super Rotation":  SongData(478, "Super Rotation", "PLUS", "TANO*C", [3, 8.9, 13.4, None]),
    "Super Abnormia":  SongData(479, "Super Abnormia", "PLUS", "オリジナル", [6, 11, 14, 14.6, None]),
}

groups = {
    "WACCA": {name for name, data, in SONG_DATA.items() if data.version == "WACCA"},
    "WACCA S": {name for name, data, in SONG_DATA.items() if data.version == "WACCA S"},
    "LILY": {name for name, data, in SONG_DATA.items() if data.version == "LILY"},
    "LILY R": {name for name, data, in SONG_DATA.items() if data.version == "LILY R"},
    "REVERSE": {name for name, data, in SONG_DATA.items() if data.version == "REVERSE"},
    "PLUS": {name for name, data, in SONG_DATA.items() if data.version == "PLUS"},
    "TANO*C（オリジナル）": {name for name, data, in SONG_DATA.items() if data.category == "TANO*C（オリジナル）"},
    "ボカロ": {name for name, data, in SONG_DATA.items() if data.category == "ボカロ"},
    "アニメ／ＰＯＰ": {name for name, data, in SONG_DATA.items() if data.category == "アニメ／ＰＯＰ"},
    "2.5次元": {name for name, data, in SONG_DATA.items() if data.category == "2.5次元"},
    "TANO*C": {name for name, data, in SONG_DATA.items() if data.category == "TANO*C"},
    "オリジナル": {name for name, data, in SONG_DATA.items() if data.category == "オリジナル"},
    "バラエティ": {name for name, data, in SONG_DATA.items() if data.category == "バラエティ"},
    "東方アレンジ": {name for name, data, in SONG_DATA.items() if data.category == "東方アレンジ"},
}